### ISSUE TITLE
Unknown error crashing parity

### ISSUE THREAD

**Issue by 5murf** [paritytech/parity-ethereum#10292] opened 2019-02-04 11:29 UTC
- **Parity Ethereum version**: 2.2.7
- **Operating system**: Ubuntu
- **Installation**: one-line installer
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

Fresh sync after deleting the DB i am getting the following:

`stack backtrace:
   0:     0x5634fc1916dd - <no info>
   1:     0x5634fc1908f2 - <no info>
   2:     0x5634fc190969 - <no info>
   3:     0x5634fc18faa6 - <no info>
   4:     0x5634fa8ad218 - <no info>
   5:     0x5634fc209c96 - <no info>
   6:     0x5634fc2097e1 - <no info>
   7:     0x5634fc2096c5 - <no info>
   8:     0x5634fc25325c - <no info>
   9:     0x5634fc249311 - <no info>
  10:     0x5634fab2b4f1 - <no info>
  11:     0x5634fab46e5f - <no info>
  12:     0x5634fa8fa76d - <no info>
  13:     0x5634fab50f5a - <no info>
  14:     0x5634fab12a92 - <no info>
  15:     0x5634faac60b9 - <no info>
  16:     0x5634fa92ac17 - <no info>
  17:     0x5634faaaac07 - <no info>
  18:     0x5634fa9bc840 - <no info>
  19:     0x5634faab0378 - <no info>
  20:     0x5634fab80424 - <no info>
  21:     0x5634fab8374c - <no info>
  22:     0x5634fabe34a2 - <no info>
  23:     0x5634fab941f9 - <no info>
  24:     0x5634fa87125d - <no info>
  25:     0x5634fa87262b - <no info>
  26:     0x5634fa87262b - <no info>
  27:     0x5634fa8a7790 - <no info>
  28:     0x5634fa8efc02 - <no info>
  29:     0x5634fa8edf39 - <no info>
  30:     0x5634fa9d9a66 - <no info>
  31:     0x5634fa86ab16 - <no info>
  32:     0x5634fbf38d41 - <no info>
  33:     0x5634fbf39795 - <no info>
  34:     0x5634fbf3c6b0 - <no info>
  35:     0x5634fc21be79 - <no info>
  36:     0x5634fbf3ba9b - <no info>
  37:     0x5634fbf332b5 - <no info>
  38:     0x5634fbf3239d - <no info>
  39:     0x5634fbf192d5 - <no info>
  40:     0x5634fbf19611 - <no info>
  41:     0x5634fbf194c8 - <no info>
  42:     0x5634fbf11f45 - <no info>
  43:     0x5634fbf3a5cc - <no info>
  44:     0x5634fbf3aa5e - <no info>
  45:     0x5634fbf3b2b1 - <no info>
  46:     0x5634fbf3c6fb - <no info>
  47:     0x5634fc21be79 - <no info>
  48:     0x5634fbf37bcf - <no info>
  49:     0x5634fc20612d - <no info>
  50:     0x5634fc1f0ce5 - <no info>
  51:     0x7f3cdb69e163 - <no info>
  52:     0x7f3cdb5aadee - <no info>
  53:                0x0 - <no info>

Thread 'jsonrpc-eventloop-0' panicked at 'byte index 2 is not a char boundary; it is inside '∀' (bytes 0..3) of `∀∂∈∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∀∂∈ℝ∧∪≡∞ ↑↗↨↻⇣ ┐┼╔╘░►$

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new`

**Comment by joshua-mir** [comment] 2019-02-04 11:38
Duplicate of #10287 https://www.parity.io/security-alert-parity-ethereum-03-02/ please reconsider having your node open to the public and update to the latest release 🙏

**Closed by joshua-mir** 2019-02-04 11:38 UTC
