### ISSUE TITLE
parity crashes on syncing classic chain

### ISSUE THREAD

**Issue by xlk3099** [paritytech/parity-ethereum#9630] opened 2018-09-24 10:02 UTC
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.0.6(stable)
- **Operating system**:  Linux
- **Installation**: one-line installer
- **Fully synchronized**: no 
- **Network**: classic
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

stack backtrace:
   0:     0x55e162395fdc - <no info>
   1:     0x55e162395d92 - <no info>
   2:     0x55e162395e08 - <no info>
   3:     0x55e162394c0a - <no info>
   4:     0x55e160e73305 - <no info>
   5:     0x55e1623f5753 - <no info>
   6:     0x55e1623bda46 - <no info>
   7:     0x55e1623bce44 - <no info>
   8:     0x55e161b2ca15 - <no info>
   9:     0x55e161a4ee65 - <no info>
  10:     0x55e1617b6dd9 - <no info>
  11:     0x55e161b47a72 - <no info>
  12:     0x55e161a781cd - <no info>
  13:     0x55e161a79617 - <no info>
  14:     0x55e161a803aa - <no info>
  15:     0x55e161b0ce7d - <no info>
  16:     0x55e16241f9c9 - <no info>
  17:     0x55e161bdf439 - <no info>
  18:     0x55e1623f81da - <no info>
  19:     0x55e1623f5d25 - <no info>
  20:     0x7f3d399676b9 - <no info>
  21:     0x7f3d3948741c - <no info>
  22:                0x0 - <no info>

Thread 'Verifier #0' panicked at 'assertion failed: rc == -1', util/journaldb/src/archivedb.rs:141

Steps to reproduce:
`parity --chain=classic --cache-size=4096 --db-compaction=ssd --pruning=archive --fat-db=on --tracing=on`

**Comment by joshua-mir** [comment] 2018-09-24 10:12
Hey, if possible can you please share some more information about your system, like the distribution you are running and your specifications; and if possible, the log messages before this panic occurs, ideally with `-l sync` enabled?

**Comment by andresilva** [comment] 2018-09-24 13:46
Can you confirm with the latest beta version instead? We fixed a related issue in #9525 but it seems it wasn't backported to stable.

**Comment by debris** [comment] 2018-09-24 15:36
@andresilva was the bug crashing the node immediately or did it cause an invalid state of the database? If the later, maybe we should advise users to rebuild their `fatdb` in case of a crash?

**Comment by cheme** [comment] 2018-09-24 17:04
I think it is a duplicate of #9180 . The fix has been backported to beta, but not stable.

**Comment by xlk3099** [comment] 2018-09-25 04:58
After changing to `beta`, the crash goes away.

**Closed** 2018-09-25 10:01 UTC
Labels: F1-panic 🔨, M4-core ⛓
