### ISSUE TITLE
Thread '<unnamed>' panicked at 'other was less than the current instant', libstd/sys/unix/time.rs:292

### ISSUE THREAD

**Issue by 0x-genesys** [paritytech/parity-ethereum#9337] opened 2018-08-10 10:23 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: Parity/v1.10.8-stable-bd20c45-20180628/x86_64-linux-gnu/rustc1.27.0
> - **Which operating system?**:  Linux
> - **How installed?**:  from source
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**:  yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I ran:

> nohup parity --mode active --tracing off --pruning fast --db-compaction ssd --cache-size 3072 --geth --jsonrpc-hosts all  --jsonrpc-port 8545 -lsync,tpc=debug --log-file log.txt --jsonrpc-interface all &

Error:

```
2018-08-10 11:32:10  IO Worker #1 TRACE sync  110 <- Transactions (64 entries)
2018-08-10 11:32:10  IO Worker #1 DEBUG sync  Sent up to 64 transactions to 1 peers.
2018-08-10 11:32:10  IO Worker #2 TRACE sync  Skipping warp sync. State: Idle


====================

stack backtrace:
   0:     0x562a488d23fc - <no info>

Thread '<unnamed>' panicked at 'other was less than the current instant', libstd/sys/unix/time.rs:292

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new
```

**Comment by Tbaut** [comment] 2018-08-10 13:39
Thanks for reporting it. This is a duplicate of #8444 
Please follow this thread.

**Closed by Tbaut** 2018-08-10 13:39 UTC
