### ISSUE TITLE
The bug of validator set contract, how to solve this ?

### ISSUE THREAD

**Issue by viking2015** [paritytech/parity-ethereum#10087] opened 2018-12-19 13:33 UTC
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: v2.1.10
- **Operating system**: Linux
- **Installation**:  built from source
- **Fully synchronized**:  yes
- **Network**: private-poa
- **Restarted**: no 

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

2018-12-19 13:02:23 UTC main INFO parity_ethereum::run  Starting Parity-Ethereum/v2.1.10-stable-b47e064-20181213/x86_64-linux-gnu/rustc1.31.0
2018-12-19 13:02:23 UTC main INFO parity_ethereum::run  Keys path /home/ubuntu/DFChain/deploy/aura/node4/parity/keys/DemoPoA
2018-12-19 13:02:23 UTC main INFO parity_ethereum::run  DB path /home/ubuntu/DFChain/deploy/aura/node4/parity/chains/DemoPoA/db/8683a0755a596f74
2018-12-19 13:02:23 UTC main INFO parity_ethereum::run  State DB configuration: fast
2018-12-19 13:02:23 UTC main INFO parity_ethereum::run  Operating mode: active
2018-12-19 13:02:23 UTC main INFO ethcore_service::service  Configured for DemoPoA using AuthorityRound engine
2018-12-19 13:02:23 UTC main TRACE engine  Setting up contract caller.
2018-12-19 13:02:58 UTC IO Worker #1 INFO import     0/25 peers      8 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
2018-12-19 13:03:28 UTC IO Worker #2 INFO import     0/25 peers      8 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
2018-12-19 13:03:58 UTC IO Worker #2 INFO import     0/25 peers      8 KiB chain    7 KiB db  0 bytes queue 448 bytes sync  RPC:  0 conn,    0 req/s,    0 µs
2018-12-19 13:04:24 UTC IO Worker #0 DEBUG engine  Zooming to epoch for block 0xa6e0…9b41

====================

stack backtrace:
   0:     0x559d6f127c2d - backtrace::backtrace::trace::h9cba09a270894780
   1:     0x559d6f126e42 - <backtrace::capture::Backtrace as core::default::Default>::default::h2d345f667ea34cba
   2:     0x559d6f126eb9 - backtrace::capture::Backtrace::new::hf3eec8642311a0b2
   3:     0x559d6f125ff6 - panic_hook::gen_panic_msg::h7b5e21c89f35fc42
   4:     0x559d6da5e4b8 - panic_hook::set_with::{{closure}}::hdffd676768cd82e5
   5:     0x559d6f19f516 - std::panicking::rust_panic_with_hook::h71214e7ce0f7ac01
                        at libstd/panicking.rs:480
   6:     0x559d6f19f061 - std::panicking::continue_panic_fmt::ha8b8442f4ea9bcac
                        at libstd/panicking.rs:390
   7:     0x559d6f19ef45 - rust_begin_unwind
                        at libstd/panicking.rs:325
   8:     0x559d6f1e903c - core::panicking::panic_fmt::h0c93626b89c38af6
                        at libcore/panicking.rs:77
   9:     0x559d6e8144f9 - core::result::unwrap_failed::hb04ee4352e50f551
  10:     0x559d6e65a05d - ethcore::engines::authority_round::EpochManager::zoom_to::h5122e22957ff67c1
  11:     0x559d6e65e540 - ethcore::engines::authority_round::AuthorityRound::epoch_set::h082ad54e3338ff48
  12:     0x559d6e66161d - <ethcore::engines::authority_round::AuthorityRound as ethcore::engines::Engine<ethcore::machine::EthereumMachine>>::generate_seal::ha7db97a68c107298
  13:     0x559d6e895e83 - <ethcore::miner::miner::Miner as ethcore::miner::MinerService>::update_sealing::hcf909f50cf25415d
  14:     0x559d6e65f4f0 - <ethcore::engines::authority_round::TransitionHandler as ethcore_io::IoHandler<()>>::timeout::hebad16ff08cc1705
  15:     0x559d6e870a3e - ethcore_io::worker::Worker::work_loop::h5c0d2b4620a73848
  16:     0x559d6e634c68 - std::sys_common::backtrace::__rust_begin_short_backtrace::h71a26d78574acaa9
  17:     0x559d6e6e0996 - std::panicking::try::do_call::h3dc5da9921f9acc7
  18:     0x559d6f1b1979 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  19:     0x559d6e758d57 - <F as alloc::boxed::FnBox<A>>::call_box::h2137ad7c234a0bcc
  20:     0x559d6f19b9ad - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::he3acfc8f1203786f
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h5213f803a61d7811
                        at libstd/sys_common/thread.rs:24
  21:     0x559d6f186425 - std::sys::unix::thread::Thread::new::thread_start::he89121f566d2a8c7
                        at libstd/sys/unix/thread.rs:90
  22:     0x7f883e3d36b9 - start_thread
  23:     0x7f883def341c - clone
  24:                0x0 - <unknown>

Thread 'IO Worker #0' panicked at 'proof produced by this engine; therefore it is valid; qed: Error(Decoder(RlpExpectedToBeList), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })', libcore/result.rs:1009

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new

2018-12-19 13:04:24 UTC main INFO parity_ethereum::run  Finishing work, please wait...

Anybody know how to solve this bug? thanks very much!

**Comment by joshua-mir** [comment] 2018-12-19 13:39
Duplicate of https://github.com/paritytech/parity-ethereum/issues/9509 - can you read through that and make sure your chainspec is correctly formatted?

**Closed by joshua-mir** 2018-12-19 13:39 UTC
