### ISSUE TITLE
New Parity Beta Issues (upon reset of chain data)

### ISSUE THREAD

**Issue by Dycedlp** [paritytech/parity-ethereum#9982] opened 2018-11-28 15:33 UTC
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.2.1beta
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**:  yes
- **Network**: private
- **Restarted**: yes

---
When I updated to the new parity-ethereum beta.  I deleted my blockchain data stored in the ~ folder.  I left the same node.toml's.  I can metamask into the account I prefunded, when I send something it just becomes approved, but never gets confirmed or shows up on the explorer.  I have two sealers, but was previously just using one of those nodes & it worked perfect.  Wondering if theres missing/conflicting old chain data thats hidden.  Or if theres a problem with the new parity... Also now when I stop my parity instance, it never stops returning in a Shutdown is taking longer than expected.
2018-11-28 10:23:25  Error queueing cull: Mio(Custom { kind: ConnectionAborted, error: StringError("Network IO notification error") })
when trying to exit...  Not sure how to fix this.  After five or six minutes it said "  Shutdown timeout reached, exiting uncleanly."

**Comment by Dycedlp** [comment] 2018-11-28 15:58
Also I'm wondering what allow-ips=public does as well. Think this could be causing the issue potentially.

**Comment by joshua-mir** [comment] 2018-12-02 19:02
Closing this as it's a duplicate of your newer issue, please continue the conversation there.

**Closed by joshua-mir** 2018-12-02 19:02 UTC
Labels: Z1-question 🙋‍♀️, Z7-duplicate 🖨
