### ISSUE TITLE
bug-20190320

### ISSUE THREAD

**Issue by crazypool2019** [paritytech/parity-ethereum#10498] opened 2019-03-21 02:29 UTC
- **Parity Ethereum version**: 2.3.7-STABLE
- **Operating system**: Linux - ubuntu 16.04 64bits
- **Installation**: download from release
- **Fully synchronized**: yes
- **Network**: classic 
- **Restarted**: no / yes

parity --chain classic --no-periodic-snapshot --no-ws --pruning fast --cache-size 2048 --min-peers 25 --max-peers 200 --extra-data "ETC.POOL.ORG"  --identity "ETC.POOL.ORG" --author "0xa74e...bb" --jsonrpc-hosts all --port 3...0 --jsonrpc-port 8..0 --unlock "0xa74e....bb" --password ~/password.txt

![image](https://user-images.githubusercontent.com/45013538/54730482-f7a4d400-4b67-11e9-91b3-90d3f0b2e3ab.png)

**Comment by joshua-mir** [comment] 2019-03-21 08:29
Duplicate of #10492

**Closed by joshua-mir** 2019-03-21 08:29 UTC
Labels: Z7-duplicate 🖨
