### ISSUE TITLE
Parity Ropsten upgrade from 2.1.10 to 2.2.8 restarts syncing from genesis block

### ISSUE THREAD

**Issue by nostdm** [paritytech/parity-ethereum#10275] opened 2019-02-01 14:18 UTC
I had deployed and fully synced a Parity Ropsten node version **2.1.10** with the `--pruning=archive` option. 

It finished syncing a few days ago and is currently at the latest Ropsten block - the same block that ropsten.etherscan.io shows (currently **4936368**).

However, I'm trying to upgrade to the latest version of Parity (**2.2.8**), but when I upgrade the node to version **2.2.8**, it starts syncing from the genesis block instead of reusing the existing state.

In the past when I upgraded the Parity version it would reuse the old state and keep syncing - in the worst case it would re-org the bad blocks, but with the latest version it seems to create a new state trie and starts syncing from the beginning.

**Comment by joshua-mir** [comment] 2019-02-01 15:03
Hey @nostdm I'm closing this as it's a duplicate of #10248

**Closed by joshua-mir** 2019-02-01 15:03 UTC
