### ISSUE TITLE
[Light client] Substantial slow down in header sync

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-ethereum#9879] opened 2018-11-07 16:30 UTC
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: v2.1.3-beta-
- **Operating system**: Windows and Linux
- **Installation**: binary
- **Fully synchronized**: no
- **Network**: kovan
- **Restarted**: yes

When syncing from the latest hardcoded header (`--light db kill` before syncing), the light client starts to download headers at a high rate (x000 hdr/s), and then it slows down quite substantially (x00 hdr/s). 

```bash
2018-11-07 17:07:14  Starting Parity-Ethereum/v2.1.3-beta-18ddd7c-20181015/x86_64-linux-gnu/rustc1.29.0
2018-11-07 17:07:14  Keys path /home/thib/.local/share/io.parity.ethereum/keys/kovan
2018-11-07 17:07:14  DB path /home/thib/.local/share/io.parity.ethereum/chains_light/kovan/db/9bf388941c25ea98
2018-11-07 17:07:14  Running in experimental Light Client mode.
2018-11-07 17:07:14  Debug API is not available in light client mode.
2018-11-07 17:07:14  Debug API is not available in light client mode.
2018-11-07 17:07:16  Imported #9094915 0x21ff…aaef (0.35 Mgas)
2018-11-07 17:07:17  Imported #9099267 0xded5…215f (0.36 Mgas) + another 255 header(s)
2018-11-07 17:07:19  Syncing #9106658 0xce5a…81f9  2553.6 hdr/s      0+16127 Qed  13/50 peers   10 MiB cache 12 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2018-11-07 17:07:19  Public node URL: enode://8c820b97320e978b841fe62fed9a6ac2baca0ff59abe40460d2fba7e062ebe3ec4ad48c815a9656d9b26ba3f593640bb4ac4347fcbf0362637770d724b96d7c2@192.168.1.159:30303
2018-11-07 17:07:20  Imported #9109507 0x577b…8203 (0.76 Mgas) + another 255 header(s)
2018-11-07 17:07:24  Syncing #9128846 0x0f91…00e3  4437.6 hdr/s      0+15615 Qed  14/50 peers   10 MiB cache 12 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2018-11-07 17:07:24  Imported #9128963 0x2414…23ee (0.28 Mgas) + another 255 header(s)
2018-11-07 17:07:29  Syncing #9145090 0x6e1b…4667  3248.8 hdr/s      0+    0 Qed  13/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2018-11-07 17:07:30  Imported #9145091 0x9e44…c04d (0.23 Mgas)
2018-11-07 17:07:34  Syncing #9145858 0x67e2…0949   153.6 hdr/s      0+    0 Qed  13/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2018-11-07 17:07:34  Imported #9145859 0x85fe…b4c8 (1.52 Mgas)
2018-11-07 17:07:39  Syncing #9146882 0x3200…d05b   204.8 hdr/s      0+    0 Qed  14/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2018-11-07 17:07:40  Imported #9146883 0x81d9…c030 (0.62 Mgas)
2018-11-07 17:07:44  Syncing #9147394 0xa81b…208c   102.4 hdr/s      0+    0 Qed  16/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
```
if I `ctrl-C` and relauch, the rate is quite high again for a couple seconds, and then goes back down.
```bash
2018-11-07 17:23:56  Starting Parity-Ethereum/v2.1.3-beta-18ddd7c-20181015/x86_64-linux-gnu/rustc1.29.0
2018-11-07 17:23:56  Keys path /home/thib/.local/share/io.parity.ethereum/keys/kovan
2018-11-07 17:23:56  DB path /home/thib/.local/share/io.parity.ethereum/chains_light/kovan/db/9bf388941c25ea98
2018-11-07 17:23:56  Running in experimental Light Client mode.
2018-11-07 17:23:57  Debug API is not available in light client mode.
2018-11-07 17:23:57  Debug API is not available in light client mode.
2018-11-07 17:23:59  Imported #9160196 0x24d1…7434 (1.59 Mgas)
2018-11-07 17:24:00  Imported #9161524 0x3d7b…d4ad (0.31 Mgas) + another 255 header(s)
2018-11-07 17:24:02  Syncing #9165110 0xe396…6442   983.0 hdr/s      0+29775 Qed  10/50 peers   5 MiB cache 23 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2018-11-07 17:24:02  Public node URL: enode://8c820b97320e978b841fe62fed9a6ac2baca0ff59abe40460d2fba7e062ebe3ec4ad48c815a9656d9b26ba3f593640bb4ac4347fcbf0362637770d724b96d7c2@192.168.1.159:30303
2018-11-07 17:24:07  Syncing #9181222 0xcf8c…ecef  3222.4 hdr/s      0+29132 Qed   9/50 peers   10 MiB cache 22 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2018-11-07 17:24:12  Syncing #9198132 0x62b4…eb49  3382.0 hdr/s      0+12239 Qed  10/50 peers   10 MiB cache 9 MiB queue  RPC:  0 conn,    0 req/s,    0 µs
2018-11-07 17:24:17  Syncing #9210627 0x96c5…eecb  2499.0 hdr/s      0+    0 Qed   9/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs
2018-11-07 17:24:17  Imported #9210628 0x7c99…41d2 (0.02 Mgas)
2018-11-07 17:24:22  Syncing #9210883 0x4786…45c3    51.2 hdr/s      0+    0 Qed   9/50 peers   10 MiB cache 0 bytes queue  RPC:  0 conn,    0 req/s,    0 µs

```
Note that the light client alternates between `Imported` and `Syncing`, while the top of the chain is still very far (9.3M as of writing, and the client is at 9.1M)

We originally thought that it was due to RPC sent from Fether, but this also happens without fether attached.

**Comment by ngotchac** [comment] 2018-11-28 12:09
Duplicate of #9880

**Closed by ngotchac** 2018-11-28 12:09 UTC
Labels: F3-annoyance 💩, M4-core ⛓
