### ISSUE TITLE
Parity doesn't restart after disk full

### ISSUE THREAD

**Issue by phahulin** [paritytech/parity-ethereum#11055] opened 2019-09-16 08:04 UTC
- **Parity Ethereum version**: 2.5.7
- **Operating system**: AWS Linux
- **Installation**: binary
- **Fully synchronized**: yes
- **Network**: ropsten
- **Restarted**: yes

Disk was running full on our ropsten archive node and parity service crashed.
The problem is that parity wouldn't start after disk volume was increased, looks like db got corrupted
```
Failed to open database Custom { kind: Other, error: StringError("IO error: While opening a file for sequentially reading: /data/parity_data/chains/ropsten/db/ae90623718e47d66/archive/db/MANIFEST-000003: No such file or directory") }
```
Indeed, there was no such file.

**Comment by joshua-mir** [comment] 2019-09-16 08:07
I'll need to go back through other issues, but we are aware that we don't fail gracefully when you run out of disk space while parity is running.

**Comment by macdasi** [comment] 2019-10-22 06:50
+1

**Comment by dvdplm** [comment] 2019-10-22 09:09
@joshua-mir this is probably a dupe of an existing ticket?

**Comment by joshua-mir** [comment] 2019-10-22 09:22
@dvdplm None that are currently open - and this issue is probably easier to reference than one of the multiple db corruption issues of unknown source.

**Comment by joshua-mir** [comment] 2019-10-22 09:23
Related: #10162

**Comment by joshua-mir** [comment] 2019-10-22 09:24
Closing as duplicate actually

**Closed by joshua-mir** 2019-10-22 09:24 UTC
Labels: F3-annoyance 💩, M4-io 💾, Z7-duplicate 🖨
