### ISSUE TITLE
Block verification fails at block #5435345

### ISSUE THREAD

**Issue by natamartchouk** [paritytech/parity-ethereum#11279] opened 2019-11-21 12:41 UTC
- **Parity Ethereum version**: 2.5.1
- **Operating system**: Linux
- **Installation**: docker
- **Fully synchronized**: no (because of the error)
- **Network**: rinkeby
- **Restarted**: yes

Block verification fails at block #5435345 and then the sync is not possible.

Parity runs with ```--chain rinkeby --jsonrpc-apis "eth,net,web3,personal,parity" --jsonrpc-interface all --allow-ips public --no-discovery --no-ancient-blocks```

An excerpt from the logs.
```
2019-11-21 11:24:27 UTC Stage 5 block verification failed for #5435345 (0x996c…dcb1)
Error: Error(Block(InvalidStateRoot(Mismatch { expected: 0xd70e2befca74a9b6ce0d0d52639da4b487e47f6b50251fe3a0c9889b6f615a21, found: 0x67bc5c082c0381fa4352b62c6de8a227ef8bb3a7103d646f643d7e3a27bc65bb })), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0:     0x564f2b2dcf5d - <no info>
   1:     0x564f2b2dc322 - <no info>
   2:     0x564f2b0358a8 - <no info>
   3:     0x564f2b035bd5 - <no info>
   4:     0x564f2aab1aaa - <no info>
   5:     0x564f2a8f719f - <no info>
   6:     0x564f2a913f9d - <no info>
   7:     0x564f2a34f8f0 - <no info>
   8:     0x564f2a354ef0 - <no info>
   9:     0x564f2a363267 - <no info>
  10:     0x564f2a36509c - <no info>
  11:     0x564f2a3517dc - <no info>
  12:     0x564f2a3529d2 - <no info>
  13:     0x564f2a364746 - <no info>
  14:     0x564f2a3523f7 - <no info>
  15:     0x564f2a351f80 - <no info>
  16:     0x564f2a35281a - <no info>
  17:     0x564f2a352c73 - <no info>
  18:     0x564f2a35d5c8 - <no info>
  19:     0x564f2a356be6 - <no info>
  20:     0x564f2b355bc9 - <no info>
  21:     0x564f2a361257 - <no info>
  22:     0x564f2b354f0d - <no info>
  23:     0x7f0cddbea6b9 - <no info>
  24:     0x7f0cdd70a41c - <no info>
  25:                0x0 - <no info>) } })
2019-11-21 11:24:28 UTC 
Bad block detected: Error(Block(InvalidStateRoot(Mismatch { expected: 0xd70e2befca74a9b6ce0d0d52639da4b487e47f6b50251fe3a0c9889b6f615a21, found: 0x67bc5c082c0381fa4352b62c6de8a227ef8bb3a7103d646f643d7e3a27bc65bb })), State { next_error: None, backtrace: InternalBacktrace { backtrace: Some(stack backtrace:
   0:     0x564f2b2dcf5d - <no info>
   1:     0x564f2b2dc322 - <no info>
   2:     0x564f2b0358a8 - <no info>
   3:     0x564f2b035bd5 - <no info>
   4:     0x564f2aab1aaa - <no info>
   5:     0x564f2a8f719f - <no info>
   6:     0x564f2a913f9d - <no info>
   7:     0x564f2a34f8f0 - <no info>
   8:     0x564f2a354ef0 - <no info>
   9:     0x564f2a363267 - <no info>
  10:     0x564f2a36509c - <no info>
  11:     0x564f2a3517dc - <no info>
  12:     0x564f2a3529d2 - <no info>
  13:     0x564f2a364746 - <no info>
  14:     0x564f2a3523f7 - <no info>
  15:     0x564f2a351f80 - <no info>
  16:     0x564f2a35281a - <no info>
  17:     0x564f2a352c73 - <no info>
  18:     0x564f2a35d5c8 - <no info>
  19:     0x564f2a356be6 - <no info>
  20:     0x564f2b355bc9 - <no info>
  21:     0x564f2a361257 - <no info>
  22:     0x564f2b354f0d - <no info>
  23:     0x7f0cddbea6b9 - <no info>
  24:     0x7f0cdd70a41c - <no info>
  25:                0x0 - <no info>) } })
RLP: f90b60f9025ca0a685c2fe5202b14f402d132e425ff95aaaa0046e23d82784fb49f7ad6e3211daa01dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347940000000000000000000000000000000000000000a0d70e2befca74a9b6ce0d0d52639da4b487e47f6b50251fe3a0c9889b6f615a21a0db1cf8a5f207b143b629620427c932ba48f901a669ab4158260d39e529127fa8a0e235bb93a2379d7e362b4b909186adf7022eed92198e9257f77e5b3ce690bc62b90100000000000000000000000040000000000000000000000000000004000000000000000100000000000000200000000000000000000200100000000000000000000000000000000200102020080000004000800000000000000000000000090000000000000a0000000000000200000800000040000000000000001030000000000000000000000000000000000000010000010010000000040000000004000000000000000020020000000000000400000000000000000000000000020000000000000002000000000000600000000000000000000000080000000000000020200000000000002000000000200000000000000000000000000000000000800000028352efd1836ad830830ad308845dcc49c1b861d883010905846765746888676f312e31312e35856c696e757800000000000000edde085d5a0d8208787e13aaf0960bbb59d1ca14c3ebe81308c62d686188922028562b78c2f0a54f55c16ac1a18548240617846d4add8ebed0384fc896e677a800a00000000000000000000000000000000000000000000000000000000000000000880000000000000000f908fdf8ac821bd58504a817c800833d090094d6835a70ac85c51a0844baad61be7ff5d470036080b844a9059cbb000000000000000000000000fe41cb079f7a7fc20a766c27385b989ea7354eaa0000000000000000000000000000000000000000000000004563918244f400002ba0a3c675277ac94ba43f760716db614037d36a918de1dc2b0d99041d0680cd8b68a04678f07311bbe925ac8497cffb0469396b197668d377b99474e07f68851a8838f86b8226558502540be40083081650941804b95800847db03ca376fb34344ffaa91d3ce86484d0e30db01ba0c8ecec74b16a10a28e1f723770731c51377410c38f04e1bc10b8939fc52a5967a07780357c8c1f9385d699a2819cf100e59dd6642b0e5ea8f5a82eec9b79cebc1cf9012b83038b43843b9aca00827f65946adf64fc26d495445a3cab545ac808d66932ac1580b8c458666c04000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000647b2270726f746f636f6c223a22616c6570682d6f6666636861696e222c2276657273696f6e223a312c22636f6e74656e74223a22516d576e634b6d3154364a57527a50677a6247557338654a674b556d627065774173465578594345784c71667444227d000000000000000000000000000000000000000000000000000000002ba00d7bff7be00af099eaa5d76d9b8d038c978a0ab6488ca20f7b9d66897373897fa03c98666fdfb2eb63b4e28efdbfc009b8538ecd1083349da9a10eafdd9ca74e50f8eb823f97843b9aca00830493e094653909812129804e6969fd366036cb91634f0b0480b884cb9716a700000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000e3134322e31312e3231302e3133320000000000000000000000000000000000001ca0e7ab0d3eeab3eac6e893afeade13e886e96e0b150deb017d820e9b0a8db187dda026bc0aa610ebc1f7a9bd0cf7b9856b5b317fc2f2c77921eca86a8da4133eeffff88a8301dd5a843b9aca0083015f90940964d7526b87bbf809c74ef73c5ed27f8b075d5b80a3535701d2b02efd88280a234083a520b3c0610b38eeca2a43670739c8b321f4b86ccee42ca0b9544422664c688ad219360b82ee614e4dffee4e3d9f087c00ee975208f6c027a07ddf7f4d9a66da77653993f95268552c1c2764332965face4e434a968a44def6f9028c82243b843b9aca008313e3cb94aea9a49ded76f9954dcd41e988ee68eea550cf4780b90224f3e2e6170000000000000000000000000000000000000000000000000005972ef0998b74000000000000000000000000609cfb04cbb14fe8ddc804f10100a7e2a833e44f000000000000000000000000000000000000000000000000000000000000016000000000000000000000000000000000000000000000000000000000000001a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000007e300000000000000000000000000000000000000000000000000000000000001c000000000000000000000000000000000000000000000000000000000000001e00000000000000000000000000000000000000000000000000000000000000064000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000b746573745f626f74746c6500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002ba098cd6bc33f4178630df5c971a695ece6f3e61aac47cd11c054e2471f9e209956a06d32eacc9a665cf3d860a81aee181d8f4e7df8319381233d5b7c1a80e0a06855f9017b8256a4843b9aca0082c350946da74a271c51ac4b7b5a81a30059b38d5481ff7380b901147b2267756964223a202235613739356330612d653263392d346662332d386466332d303631356163333935643565222c2022736861353132223a20223139376234396135646136313564396266643834356564353863643266386630623761643562653630663031303965613938613062656635613331333038613538393763386535633463343936626233613938356261666536343739653561316264623061643266663131633666386565666434313738393130326564343739222c20226964656e74696669636174696f6e223a202264653233613836373336366430396434383265376234316439336264656237613366313133643139376134373334363330313364323831633762366136303939227d1ba0599671e5964e1ac492393f55228153e6a34f21a2353d370663cd4347fc896ed9a078b48ebdef52e2b393dd5ca028e337613ef5e719f61c6e330fea76f29d1f6762f9012b82d240843b9aca00834c4b4094fea2cf9c0384747e068f0798c62bb74bd6f4bcb880b8c40bc757e000000000000000000000000000000000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000a6b6f64652d6f72636831000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000006546573744d4c00000000000000000000000000000000000000000000000000002ca0f754750f0da23f2cfa604bad477b31d1f0d641a30f3f37a5a1357a8c1cd84d96a068c1d7be6a0b84410dce094e375de1d772b77cb2f79cee774e1f83c01c08ed38c0
Header: Header { parent_hash: 0xa685c2fe5202b14f402d132e425ff95aaaa0046e23d82784fb49f7ad6e3211da, timestamp: 1573669313, number: 5435345, author: 0x0000000000000000000000000000000000000000, transactions_root: 0xdb1cf8a5f207b143b629620427c932ba48f901a669ab4158260d39e529127fa8, uncles_hash: 0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347, extra_data: [216, 131, 1, 9, 5, 132, 103, 101, 116, 104, 136, 103, 111, 49, 46, 49, 49, 46, 53, 133, 108, 105, 110, 117, 120, 0, 0, 0, 0, 0, 0, 0, 237, 222, 8, 93, 90, 13, 130, 8, 120, 126, 19, 170, 240, 150, 11, 187, 89, 209, 202, 20, 195, 235, 232, 19, 8, 198, 45, 104, 97, 136, 146, 32, 40, 86, 43, 120, 194, 240, 165, 79, 85, 193, 106, 193, 161, 133, 72, 36, 6, 23, 132, 109, 74, 221, 142, 190, 208, 56, 79, 200, 150, 230, 119, 168, 0], state_root: 0xd70e2befca74a9b6ce0d0d52639da4b487e47f6b50251fe3a0c9889b6f615a21, receipts_root: 0xe235bb93a2379d7e362b4b909186adf7022eed92198e9257f77e5b3ce690bc62, log_bloom: 0x000000000000000000000040000000000000000000000000000004000000000000000100000000000000200000000000000000000200100000000000000000000000000000000200102020080000004000800000000000000000000000090000000000000a0000000000000200000800000040000000000000001030000000000000000000000000000000000000010000010010000000040000000004000000000000000020020000000000000400000000000000000000000000020000000000000002000000000000600000000000000000000000080000000000000020200000000000002000000000200000000000000000000000000000000000800000, gas_used: 709384, gas_limit: 7002160, difficulty: 2, seal: [[160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [136, 0, 0, 0, 0, 0, 0, 0, 0]], hash: Some(0x996cb7cfa06de2348e804bd0dd28ff34aabd7e74529af9961b1afc8ce33cdcb1) }
Uncles: 
Transactions:[Tx 0] UnverifiedTransaction { unsigned: Transaction { nonce: 7125, gas_price: 20000000000, gas: 4000000, action: Call(0xd6835a70ac85c51a0844baad61be7ff5d4700360), value: 0, data: [169, 5, 156, 187, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 254, 65, 203, 7, 159, 122, 127, 194, 10, 118, 108, 39, 56, 91, 152, 158, 167, 53, 78, 170, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 69, 99, 145, 130, 68, 244, 0, 0] }, v: 43, r: 74077638606589943655870844595270783758475342327542948136738819890223818574696, s: 31875580569986760712782690368338928702842395597650028005271258469229422872632, hash: 0x8b40b5d2b5da0be96dfd1e99f06a9e24131dc5ecfd2b98b8b08af6329776aea5 }
[Tx 1] UnverifiedTransaction { unsigned: Transaction { nonce: 9813, gas_price: 10000000000, gas: 530000, action: Call(0x1804b95800847db03ca376fb34344ffaa91d3ce8), value: 100, data: [208, 227, 13, 176] }, v: 27, r: 90881177582116540566462206126551369331459546795456404474416107537569304697191, s: 54051754556046810591098568107392131088538979196854577074877775216135774321692, hash: 0x84a0105351e08983e132aa77aa8f7285722011cad7ce599f9574ff8d500b60d2 }
[Tx 2] UnverifiedTransaction { unsigned: Transaction { nonce: 232259, gas_price: 1000000000, gas: 32613, action: Call(0x6adf64fc26d495445a3cab545ac808d66932ac15), value: 0, data: [88, 102, 108, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100, 123, 34, 112, 114, 111, 116, 111, 99, 111, 108, 34, 58, 34, 97, 108, 101, 112, 104, 45, 111, 102, 102, 99, 104, 97, 105, 110, 34, 44, 34, 118, 101, 114, 115, 105, 111, 110, 34, 58, 49, 44, 34, 99, 111, 110, 116, 101, 110, 116, 34, 58, 34, 81, 109, 87, 110, 99, 75, 109, 49, 84, 54, 74, 87, 82, 122, 80, 103, 122, 98, 71, 85, 115, 56, 101, 74, 103, 75, 85, 109, 98, 112, 101, 119, 65, 115, 70, 85, 120, 89, 67, 69, 120, 76, 113, 102, 116, 68, 34, 125, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }, v: 43, r: 6099152505536529701117298555627763515141123692077331579366660264728292723071, s: 27408038663081994662921252509739168133144986023436277529783498131086596591184, hash: 0xd8478cf49df784610579d7d7b69df72507938c9dd02b9a61247339223cddb5c0 }
[Tx 3] UnverifiedTransaction { unsigned: Transaction { nonce: 16279, gas_price: 1000000000, gas: 300000, action: Call(0x653909812129804e6969fd366036cb91634f0b04), value: 0, data: [203, 151, 22, 167, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 14, 49, 52, 50, 46, 49, 49, 46, 50, 49, 48, 46, 49, 51, 50, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }, v: 28, r: 104786490289747930926719303734736395099477296482094295932129824953706612885469, s: 17520128988939055417880240145287443097163341666452545527175342004902039580671, hash: 0x3591324b346429b196e7901d29f01624e6ea53ac2baff93509b753f98970b155 }
[Tx 4] UnverifiedTransaction { unsigned: Transaction { nonce: 122202, gas_price: 1000000000, gas: 90000, action: Call(0x0964d7526b87bbf809c74ef73c5ed27f8b075d5b), value: 0, data: [83, 87, 1, 210, 176, 46, 253, 136, 40, 10, 35, 64, 131, 165, 32, 179, 192, 97, 11, 56, 238, 202, 42, 67, 103, 7, 57, 200, 179, 33, 244, 184, 108, 206, 228] }, v: 44, r: 83826762387508720903939443345877985715485766350386942261224059424376601624615, s: 56933991582316218369483143919260740036249355686703448613192675866269582679798, hash: 0xebeb42a73da4097c536da95859cd82c792d34b582e7edadafb30c22dbf9ca658 }
[Tx 5] UnverifiedTransaction { unsigned: Transaction { nonce: 9275, gas_price: 1000000000, gas: 1303499, action: Call(0xaea9a49ded76f9954dcd41e988ee68eea550cf47), value: 0, data: [243, 226, 230, 23, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 151, 46, 240, 153, 139, 116, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 96, 156, 251, 4, 203, 177, 79, 232, 221, 200, 4, 241, 1, 0, 167, 226, 168, 51, 228, 79, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 96, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 160, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 227, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 192, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 224, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 11, 116, 101, 115, 116, 95, 98, 111, 116, 116, 108, 101, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }, v: 43, r: 69114500383646373783526119837372849081751806340528209973464462918348892576086, s: 49392063373549427291939129670431943939526422348722930044232173867262854326357, hash: 0x496277668c1181cbe9d72e9a62d538af11bb1a95c72d4aa0028c7fe2bffb6b6e }
[Tx 6] UnverifiedTransaction { unsigned: Transaction { nonce: 22180, gas_price: 1000000000, gas: 50000, action: Call(0x6da74a271c51ac4b7b5a81a30059b38d5481ff73), value: 0, data: [123, 34, 103, 117, 105, 100, 34, 58, 32, 34, 53, 97, 55, 57, 53, 99, 48, 97, 45, 101, 50, 99, 57, 45, 52, 102, 98, 51, 45, 56, 100, 102, 51, 45, 48, 54, 49, 53, 97, 99, 51, 57, 53, 100, 53, 101, 34, 44, 32, 34, 115, 104, 97, 53, 49, 50, 34, 58, 32, 34, 49, 57, 55, 98, 52, 57, 97, 53, 100, 97, 54, 49, 53, 100, 57, 98, 102, 100, 56, 52, 53, 101, 100, 53, 56, 99, 100, 50, 102, 56, 102, 48, 98, 55, 97, 100, 53, 98, 101, 54, 48, 102, 48, 49, 48, 57, 101, 97, 57, 56, 97, 48, 98, 101, 102, 53, 97, 51, 49, 51, 48, 56, 97, 53, 56, 57, 55, 99, 56, 101, 53, 99, 52, 99, 52, 57, 54, 98, 98, 51, 97, 57, 56, 53, 98, 97, 102, 101, 54, 52, 55, 57, 101, 53, 97, 49, 98, 100, 98, 48, 97, 100, 50, 102, 102, 49, 49, 99, 54, 102, 56, 101, 101, 102, 100, 52, 49, 55, 56, 57, 49, 48, 50, 101, 100, 52, 55, 57, 34, 44, 32, 34, 105, 100, 101, 110, 116, 105, 102, 105, 99, 97, 116, 105, 111, 110, 34, 58, 32, 34, 100, 101, 50, 51, 97, 56, 54, 55, 51, 54, 54, 100, 48, 57, 100, 52, 56, 50, 101, 55, 98, 52, 49, 100, 57, 51, 98, 100, 101, 98, 55, 97, 51, 102, 49, 49, 51, 100, 49, 57, 55, 97, 52, 55, 51, 52, 54, 51, 48, 49, 51, 100, 50, 56, 49, 99, 55, 98, 54, 97, 54, 48, 57, 57, 34, 125] }, v: 27, r: 40521656670621414429305663174593392267051013792887846814518687969233739542233, s: 54596559470266974983087726973174223417417260783113843350608945765995021035362, hash: 0x5608a8b2028497a05067841870b23c2ab009a4da128f1c320cd3b9d43731eb19 }
[Tx 7] UnverifiedTransaction { unsigned: Transaction { nonce: 53824, gas_price: 1000000000, gas: 5000000, action: Call(0xfea2cf9c0384747e068f0798c62bb74bd6f4bcb8), value: 0, data: [11, 199, 87, 224, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10, 107, 111, 100, 101, 45, 111, 114, 99, 104, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 84, 101, 115, 116, 77, 76, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }, v: 44, r: 111870496663665760960810013739449321284068044696999547625088400796674501922198, s: 47383026745184199874842792064313701680268294551337338649792328619806775897400, hash: 0x358dd590a27a38205d8d62fbd4b3f09d7b0d7912e77bbc452462b7e0bae32a5b }

2019-11-21 11:24:28 UTC Transaction culled (hash 0xac57a474327603e800324a730427376c7081bd724d360c89720721ba1285910b)
2019-11-21 11:24:28 UTC Transaction culled (hash 0x12279a0ade37a11bf986dc9ee7edf43dd2cfd9da6a11eb2e633e4351dfc10e66)
2019-11-21 11:24:28 UTC Transaction culled (hash 0x4dfba1837ef789d0c313eb1c422fa1cb5c15d83e621410216c4745c621250afc)
2019-11-21 11:24:28 UTC Imported #5435344 0xa685…11da (6 txs, 0.56 Mgas, 812 ms, 2.21 KiB) + another 6 block(s) containing 46 tx(s)
2019-11-21 11:24:53 UTC    1/25 peers      6 MiB chain   25 MiB db  0 bytes queue   47 KiB sync  RPC:  0 conn,   64 req/s,   80 µs
2019-11-21 11:25:23 UTC    0/25 peers      6 MiB chain   25 MiB db  0 bytes queue   47 KiB sync  RPC:  0 conn,   64 req/s,   76 µs
2019-11-21 11:25:53 UTC    0/25 peers      6 MiB chain   25 MiB db  0 bytes queue   47 KiB sync  RPC:  0 conn,   63 req/s,   58 µs
2019-11-21 11:26:23 UTC    0/25 peers      6 MiB chain   25 MiB db  0 bytes queue   47 KiB sync  RPC:  0 conn,   63 req/s,   53 µs
2019-11-21 11:26:53 UTC    0/25 peers      6 MiB chain   25 MiB db  0 bytes queue   47 KiB sync  RPC:  0 conn,   63 req/s,   58 µs
2019-11-21 11:27:09 UTC Fallback to `BlockId::Latest`
2019-11-21 11:27:23 UTC    0/25 peers      6 MiB chain   25 MiB db  0 bytes queue   47 KiB sync  RPC:  0 conn,   62 req/s,   51 µs
```

**Comment by joshua-mir** [comment] 2019-11-21 12:44
@natamartchouk please update to version 2.5.10 - this issue is due to the fact that 2.5.1 does not support the Istanbul hard fork that happened on mainnet and the testnets recently.

**Comment by natamartchouk** [comment] 2019-11-21 12:50
@joshua-mir ok, thx for the quick response. mainnet seems to work fine with parity 2.5.1.

**Comment by joshua-mir** [comment] 2019-11-21 12:52
it won't come the Istanbul fork block 😅 of 9,069,000 ~ December 7th (according to https://ethernodes.org/istanbul)

**Comment by joshua-mir** [comment] 2019-11-21 12:54
also closing this as a duplicate of #11235

**Closed by joshua-mir** 2019-11-21 12:54 UTC
