### ISSUE TITLE
Thread 'Verifier #1' panicked at 'specified instant was later than self', libstd/sys/unix/time.rs:292

### ISSUE THREAD

**Issue by ChristophDFine** [paritytech/parity-ethereum#10029] opened 2018-12-07 10:24 UTC
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.0.6
- **Operating system**: Linux
- **Installation**: ubuntu package
- **Fully synchronized**: yes
- **Network**: kovan
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

Crash due to the above error message. What is worse:
It restarted and got stuck and would not continue syncing for more than 2 hours. Then I manually restarted again and it was working again. I dont see any Problems with the database so far.

```[12557]: 2018-12-06 13:14:42 UTC   13/25 peers     68 MiB chain   29 MiB db  0 bytes queue   23 KiB sync  RPC:  0 conn,    3 req/s,   97 µs
Dec  6 13:14:43 ip-10-0-0-123 parity[12557]: 2018-12-06 13:14:43 UTC Snapshot: 390905 accounts 0 blocks 302724900 bytes
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]: 2018-12-06 13:14:44 UTC Imported #9603478 0x3e48…20d9 (0 txs, 0.00 Mgas, 23 ms, 0.57 KiB)
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]: ====================
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]: stack backtrace:
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:    0:     0x556bd03c060c - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:    1:     0x556bd03c03c2 - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:    2:     0x556bd03c0438 - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:    3:     0x556bd03bf23a - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:    4:     0x556bcee67085 - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:    5:     0x556bd0420233 - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:    6:     0x556bd041ffd6 - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:    7:     0x556bd042edf8 - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:    8:     0x556bd04228a3 - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:    9:     0x556bcf9f7c6c - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:   10:     0x556bcf807067 - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:   11:     0x556bcf7d4293 - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:   12:     0x556bcf7dde74 - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:   13:     0x556bcfa8abcc - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:   14:     0x556bcf7afe19 - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:   15:     0x556bcfb4d902 - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:   16:     0x556bcfaaf385 - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:   17:     0x556bcfab0717 - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:   18:     0x556bcfab643a - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:   19:     0x556bcfb1462d - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:   20:     0x556bd044a4a9 - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:   21:     0x556bcfbe48d9 - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:   22:     0x556bd0422cba - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:   23:     0x556bd0420805 - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:   24:     0x7fd4b59aa6da - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:   25:     0x7fd4b54bb88e - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:   26:                0x0 - <no info>
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]: Thread 'Verifier #1' panicked at 'specified instant was later than self', libstd/sys/unix/time.rs:292
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]: This is a bug. Please report it at:
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]:     https://github.com/paritytech/parity/issues/new
Dec  6 13:14:44 ip-10-0-0-123 parity[12557]: 2018-12-06 13:14:44 UTC Finishing work, please wait...
Dec  6 13:15:45 ip-10-0-0-123 parity[12557]: 2018-12-06 13:15:45 UTC Shutdown is taking longer than expected.
Dec  6 13:19:45 ip-10-0-0-123 parity[12557]: 2018-12-06 13:19:45 UTC Shutdown timeout reached, exiting uncleanly.
Dec  6 13:19:46 ip-10-0-0-123 parity[12557]: 2018-12-06 13:19:46 UTC Starting Parity-Ethereum/v2.0.6-stable-549e202-20180919/x86_64-linux-gnu/rustc1.29.0
Dec  6 13:19:46 ip-10-0-0-123 parity[12557]: 2018-12-06 13:19:46 UTC Keys path /root/.local/share/io.parity.ethereum/keys/kovan
Dec  6 13:19:46 ip-10-0-0-123 parity[12557]: 2018-12-06 13:19:46 UTC DB path /root/.local/share/io.parity.ethereum/chains/kovan/db/9bf388941c25ea98
Dec  6 13:19:46 ip-10-0-0-123 parity[12557]: 2018-12-06 13:19:46 UTC State DB configuration: archive +Trace
Dec  6 13:19:46 ip-10-0-0-123 parity[12557]: 2018-12-06 13:19:46 UTC Operating mode: active
Dec  6 13:19:47 ip-10-0-0-123 parity[12557]: 2018-12-06 13:19:47 UTC Configured for Kovan using AuthorityRound engine
Dec  6 13:19:49 ip-10-0-0-123 parity[12557]: 2018-12-06 13:19:49 UTC Error importing saved transaction: Transaction error (No longer valid)
Dec  6 13:19:53 ip-10-0-0-123 parity[12557]: 2018-12-06 13:19:53 UTC Stage 5 block verification failed for #9603481 (0x1d80…c7a8)
Dec  6 13:19:53 ip-10-0-0-123 parity[12557]: Error: Error(Block(InvalidGasUsed(Mismatch { expected: 0x1156b5, found: 0x12599c })), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } })
Dec  6 13:19:54 ip-10-0-0-123 parity[12557]: 2018-12-06 13:19:54 UTC Public node URL: enode://2aca25224ed2e78a928618e37ebd149fb5adb396532fb230b652eea1c4d19df492daf1e38957756a2cc2360e61a74157b374b1792c0cd02bebb948011a8d560e@10.0.0.123:30303
Dec  6 13:20:24 ip-10-0-0-123 parity[12557]: 2018-12-06 13:20:24 UTC    1/25 peers    115 KiB chain  186 KiB db  0 bytes queue   10 KiB sync  RPC:  0 conn,    2 req/s,   95 µs
Dec  6 13:20:54 ip-10-0-0-123 parity[12557]: 2018-12-06 13:20:54 UTC    0/25 peers    115 KiB chain  186 KiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,    2 req/s,   94 µs
Dec  6 13:21:24 ip-10-0-0-123 parity[12557]: 2018-12-06 13:21:24 UTC    0/25 peers    115 KiB chain  186 KiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,    2 req/s,   93 µs
Dec  6 13:21:54 ip-10-0-0-123 parity[12557]: 2018-12-06 13:21:54 UTC    0/25 peers    115 KiB chain  186 KiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,    2 req/s,   95 µs
Dec  6 13:22:24 ip-10-0-0-123 parity[12557]: 2018-12-06 13:22:24 UTC    0/25 peers    115 KiB chain  186 KiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,    2 req/s,   94 µs
Dec  6 13:22:54 ip-10-0-0-123 parity[12557]: 2018-12-06 13:22:54 UTC    0/25 peers    115 KiB chain  186 KiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,    2 req/s,   92 µs
Dec  6 13:23:24 ip-10-0-0-123 parity[12557]: 2018-12-06 13:23:24 UTC    0/25 peers    115 KiB chain  186 KiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,    2 req/s,   94 µs
Dec  6 13:23:54 ip-10-0-0-123 parity[12557]: 2018-12-06 13:23:54 UTC    0/25 peers    115 KiB chain  186 KiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,    2 req/s,   93 µs
Dec  6 13:24:24 ip-10-0-0-123 parity[12557]: 2018-12-06 13:24:24 UTC    0/25 peers    115 KiB chain  186 KiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,    3 req/s,   93 µs
Dec  6 13:24:59 ip-10-0-0-123 parity[12557]: 2018-12-06 13:24:59 UTC    0/25 peers    115 KiB chain  186 KiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,    3 req/s,   92 µs
Dec  6 13:25:29 ip-10-0-0-123 parity[12557]: 2018-12-06 13:25:29 UTC    0/25 peers    115 KiB chain  186 KiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,    3 req/s,   93 µs
Dec  6 13:25:59 ip-10-0-0-123 parity[12557]: 2018-12-06 13:25:59 UTC    0/25 peers    115 KiB chain  186 KiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,    3 req/s,   95 µs
Dec  6 13:26:29 ip-10-0-0-123 parity[12557]: 2018-12-06 13:26:29 UTC    0/25 peers    115 KiB chain  186 KiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,    3 req/s,   93 µs
Dec  6 13:26:59 ip-10-0-0-123 parity[12557]: 2018-12-06 13:26:59 UTC    0/25 peers    115 KiB chain  186 KiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,    3 req/s,   94 µs
Dec  6 13:27:29 ip-10-0-0-123 parity[12557]: 2018-12-06 13:27:29 UTC    0/25 peers    115 KiB chain  186 KiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,    3 req/s,   91 µs
Dec  6 13:27:59 ip-10-0-0-123 parity[12557]: 2018-12-06 13:27:59 UTC    0/25 peers    115 KiB chain  186 KiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,    2 req/s,   95 µs
Dec  6 13:28:29 ip-10-0-0-123 parity[12557]: 2018-12-06 13:28:29 UTC    0/25 peers    115 KiB chain  186 KiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,    2 req/s,   93 µs
Dec  6 13:28:59 ip-10-0-0-123 parity[12557]: 2018-12-06 13:28:59 UTC    0/25 peers    115 KiB chain  186 KiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,    2 req/s,   94 µs
Dec  6 13:29:29 ip-10-0-0-123 parity[12557]: 2018-12-06 13:29:29 UTC    0/25 peers    115 KiB chain  186 KiB db  0 bytes queue   11 KiB sync  RPC:  0 conn,    2 req/s,   94 µs
Dec  6 13:29:59 ip-10-0-0-123 parity[12557]: 2018-12-06 13:29:59 UTC Syncing #9603480 0xd0be…d5d6     0.00 blk/s    0.0 tx/s    0 Mgas/s      0+    0 Qed  #9603352    2/25 peers    242 KiB chain  186 KiB db  0 bytes queue   90 KiB sync  RPC:  0 conn,    2 req/s,   95 µs
Dec  6 13:30:34 ip-10-0-0-123 parity[12557]: 2018-12-06 13:30:34 UTC    0/25 peers    242 KiB chain  186 KiB db  0 bytes queue  195 KiB sync  RPC:  0 conn,    2 req/s,   93 µs
Dec  6 13:30:54 ip-10-0-0-123 parity[12557]: 2018-12-06 13:30:54 UTC Syncing #9603480 0xd0be…d5d6     0.00 blk/s    0.0 tx/s    0 Mgas/s      0+    0 Qed  #9602457    1/25 peers    242 KiB chain  186 KiB db  0 bytes queue  195 KiB sync  RPC:  0 conn,    2 req/s,   92 µs
Dec  6 13:30:59 ip-10-0-0-123 parity[12557]: 2018-12-06 13:30:59 UTC Syncing #9603480 0xd0be…d5d6     0.00 blk/s    0.0 tx/s    0 Mgas/s      0+    0 Qed  #9602686    1/25 peers    242 KiB chain  186 KiB db  0 bytes queue  212 KiB sync  RPC:  0 conn,    2 req/s,   92 µs
Dec  6 13:31:04 ip-10-0-0-123 parity[12557]: 2018-12-06 13:31:04 UTC Syncing #9603480 0xd0be…d5d6     0.00 blk/s    0.0 tx/s    0 Mgas/s      0+    0 Qed  #9603192    1/25 peers    242 KiB chain  186 KiB db  0 bytes queue  220 KiB sync  RPC:  0 conn,    2 req/s,   93 µs
Dec  6 13:31:34 ip-10-0-0-123 parity[12557]: 2018-12-06 13:31:34 UTC    0/25 peers    242 KiB chain  186 KiB db  0 bytes queue  261 KiB sync  RPC:  0 conn,    2 req/s,   88 µs
Dec  6 13:32:05 ip-10-0-0-123 parity[12557]: 2018-12-06 13:32:05 UTC    0/25 peers    242 KiB chain  186 KiB db  0 bytes queue  261 KiB sync  RPC:  0 conn,    2 req/s,   94 µs
Dec  6 13:32:35 ip-10-0-0-123 parity[12557]: 2018-12-06 13:32:35 UTC    1/25 peers    242 KiB chain  186 KiB db  0 bytes queue  261 KiB sync  RPC:  0 conn,    2 req/s,   94 µs
Dec  6 13:33:05 ip-10-0-0-123 parity[12557]: 2018-12-06 13:33:05 UTC    1/25 peers    714 KiB chain  186 KiB db  0 bytes queue  261 KiB sync  RPC:  0 conn,    2 req/s,   94 µs
Dec  6 13:33:35 ip-10-0-0-123 parity[12557]: 2018-12-06 13:33:35 UTC    1/25 peers      1 MiB chain  186 KiB db  0 bytes queue  261 KiB sync  RPC:  0 conn,    3 req/s,   91 µs
Dec  6 13:34:05 ip-10-0-0-123 parity

**Comment by joshua-mir** [comment] 2018-12-07 10:32
This should probably be handled better than a panic. As a quick aside, is your system's time in sync?

**Comment by ChristophDFine** [comment] 2018-12-07 10:35
Yes, looks pretty much in time to the second.
But I dont know what it was at the time of the crash

**Comment by joshua-mir** [comment] 2019-02-04 12:11
closing as duplicate of #8444 (sorry I hadn't noticed earlier!)

**Closed by joshua-mir** 2019-02-04 12:11 UTC
Labels: F1-panic 🔨, M4-core ⛓, Z7-duplicate 🖨
