### ISSUE TITLE
Latest parity has some sort of memory/race issue

### ISSUE THREAD

**Issue by andrewheadricke** [paritytech/parity-ethereum#10459] opened 2019-03-07 00:11 UTC
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.3.4
- **Operating system**: Linux
- **Installation**: published binary
- **Fully synchronized**: yes
- **Network**: ethereum
- **Restarted**: yes

In the latest couple of releases (including stable) i've noticed Parity is locking up my machine after an hour or two of use.  While always consuming quite high amounts of RAM and CPU usage in the past, I never had any lockup issues before. However now, with still high RAM and CPU usage, my computer starts to freeze and stutter and lock up after parity has been running for an hour or so.

This usually happens when a program either consumes all the RAM or has a CPU race condition.  Unfortunately I have no other clues as to what might be causing it. Perhaps its as simple as some of the latest changes to Parity consume more RAM than my machine can provide.  I have 8GiB of RAM.

**Comment by joshua-mir** [comment] 2019-03-07 08:11
Duplicate of #10380, let me know if you think that is not the case here.

**Closed by joshua-mir** 2019-03-07 08:11 UTC

**Comment by andrewheadricke** [comment] 2019-03-07 10:35
it doesn't sound the same as my node does not automatically shutdown, it keeps on running but very slowly. However I just stumbled upon this issue #10361 which sounds like it could explain what i'm seeing.

**Comment by joshua-mir** [comment] 2019-03-07 10:38
Fair enough. Those two issues are two of our top priorities atm. 👍
