### ISSUE TITLE
Mining orphan and loss of peers

### ISSUE THREAD

**Issue by HaffASE** [paritytech/parity-ethereum#9715] opened 2018-10-08 08:00 UTC
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.0.6
- **Operating system**: Linux (Ubuntu)
- **Installation**: Docker
- **Fully synchronized**: no
- **Network**: ethereum / ethereum classic
- **Restarted**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

I have a problem with mining blocks, all blocks become orphans (more than 10 in row). This happens if the parity works more than 3-4 hours after the first synchronization. In the future, rebooting does not help.

I tried a different number of peers from 25 to 200, the result is the same.
Here are my startup settings

docker run -ti -d 
-p 8545:8545 -p 30303:30303 -p 30303:30303/udp 
--name parity 
--net host 
--restart always 
-v $HOME/parity/.local:/root/.local 
parity/parity:v2.0.6 
--mode active 
--chain classic 
--pruning fast 
--warp-barrier 6660000 
--no-ancient-blocks 
--no-serve-light 
--jsonrpc-interface all 
--jsonrpc-hosts all 
--min-peers 25 --max-peers 50 
--num-verifiers 2 --jsonrpc-threads 2 
--scale-verifiers 
--no-ws 
--no-ipc 
--db-compaction ssd 
--cache-size-db 1024 
--tx-queue-size 64 
--no-periodic-snapshot 
--unsafe-expose 
--relay-set strict 
--force-sealing

I recorded attach a log with 2 minutes while finding the block.

https://gist.github.com/HaffASE/d32ad8d44d2e0e77255a420aacc0bd9f

From strange, with a large number (more 100 peers), many peers are lost (see screenshot)
https://imgur.com/a/qdzYOWM

**Comment by oliverw** [comment] 2018-10-08 08:13
Could be related to #9278.

**Comment by joshua-mir** [comment] 2018-10-08 09:07
@HaffASE I would strongly recommend against using settings like `--unsafe-expose` on a mining node, as you *will* get excessive rpc requests from malicious parties attempting to slow down your node. This is likely the cause of your peering issue.

That said, as stated by oliverw above, your orphaning issue is very likely related to #9278, closing as duplicate, please reopen if this is not the case.

**Closed by joshua-mir** 2018-10-08 09:07 UTC
