### ISSUE TITLE
Massive increase in CPU usage with 1.11.1

### ISSUE THREAD

**Issue by folsen** [paritytech/parity-ethereum#8696] opened 2018-05-23 14:40 UTC
- **Which Parity version?**: 1.11.1
- **Which operating system?**: Linux
- **How installed?**: via binaries
- **Are you fully synchronized?**: yes
- **Which network are you connected to?**: ethereum
- **Did you try to restart the node?**: yes

After upgrading from latest 1.10 to 1.11.1 I use way way more CPU, while network usage is down.

![Stats](http://s.3h.se/MkdvzqYtw3.png)

**Comment by SwaroopH** [comment] 2018-05-25 20:04
Same with us. Even did a full db reset couple of days later to ensure it wasn't some background db upgrade causing the load as you can see the graph.

<img width="892" alt="screenshot 2018-05-25 13 02 41" src="https://user-images.githubusercontent.com/62628/40564047-fff2d5a4-601b-11e8-808a-2670a9c87c53.png">

**Comment by AyushyaChitransh** [comment] 2018-06-04 13:23
> I'm running:
>
> - **Which Parity version?**: v1.10.0-unstable-66755be8f-20180206/x86_64-linux-gnu/rustc1.23.0 and v1.12.0-unstable-8057e8df4-20180604/x86_64-linux-gnu/rustc1.26.1
> - **Which operating system?**: Amazon Linux
> - **How installed?**: from source
> - **Are you fully synchronized?**: yes! Fat DB and trace enabled.
> - **Which network are you connected to?**: Private network, PoA chain.
> - **Did you try to restart the node?**: so many times

**More attempts to solve this issue**: Tried following parameters: 
 - increased the CPU from 2 core to 4 core
 -  `--no-hardware-wallets` did not help.
 - `--jsonrpc-threads 1 --jsonrpc-server-threads 1`
 - `--no-ancient-blocks` also did not resolve the issue.

We are using Amazon Linux, 2 core CPU. This has been a gradual issue in our v1.10.0 versions. We received warnings for CPU usage upto 60% and then those issues transformed gradually into critical issues with CPU usage upto 104%

I am not able to pin this issue to any of these specific things:
 - a problem with parity
 - Issue with increasing blockchain size
 - Issue with server hardware configuration.

Is there any other thing/configuration which may help to resolve these CPU usage problems?

**Comment by AyushyaChitransh** [comment] 2018-06-10 08:09
In my case, I was monitoring the node using https://github.com/cubedro/eth-net-intelligence-api and as soon as I stopped the monitoring process, CPU usage came to normal in about 10 seconds. This happened three to four times.

I believe the RPC connections are causing the CPU issue in my case. If anyone else is facing this issue, can you verify if switching off RPC resolves this problem?

**Comment by tomusdrw** [comment] 2018-06-11 09:11
@AyushyaChitransh what CLI flags are you running with? Do you mind providing logs of running with `-lrpc=trace`?

**Comment by ordian** [comment] 2018-06-14 10:29
Looks like rocksdb's snappy compression may also be responsible for an increased memory usage (it takes 28.8% + 16.9% = 45.7% of total allocated memory when warp syncing):
![allocations](https://user-images.githubusercontent.com/4211399/41406999-be57a438-6fd6-11e8-93d1-262408a299aa.png)

**Comment by folsen** [comment] 2018-06-25 16:15
Seems like it is a mix of a lot of different issues, @tomusdrw has fixed some but is still working on more. I think in general we could use some more eyes on profiling and figuring out where are the cycles are spent.

**Comment by tomusdrw** [comment] 2018-06-25 16:34
In general the increased CPU usage could be caused by couple of things depending on the settings:
1. Increased peer count causing way ore communication (AES enc/dec)
2. Due to higher peer count transactions were received multiple times hence verified multitple times. In case of small queues it lead to a lot of CPU spent on ecrecover, nonce checking etc, even though the transaction was rejected eventually. This is partially addressed in #8934 second part will be addressed with rejection cache (soon)
3. With large pools creating a pending set for propagation was also exteremely expensive, even though eventually we needed only hundreds/thousands transactions to propagate (due to package size limit and internal parity limitation of txs per packet). This is addressed in #8777 
4. The last issues arethe complexity of pending transaction filter and `NonceCache` clearing.  We'll have another PRs for both (cc @andresilva )

**Comment by tomusdrw** [comment] 2018-11-08 13:58
I believe this might be closed now. Let's reopen in case there is new data available for newer version of Parity.

**Closed by tomusdrw** 2018-11-08 13:58 UTC
Labels: F7-footprint 🐾, M4-core ⛓, P2-asap 🌊
