### ISSUE TITLE
block may be skipped when subscribe new blocks

### ISSUE THREAD

**Issue by antimoth** [paritytech/parity-ethereum#9487] opened 2018-09-06 13:43 UTC
- **Parity Ethereum version**: 1.11.7
- **Operating system**: Linux
- **Installation**:  one-line installer 
- **Fully synchronized**: yes
- **Network**: kovan
- **Restarted**: yes

this is the subscribe log. block 8628749 had been skipped.
```
[DBUG][2018-09-06 20:46:44.637] ethwatcher received block                module=ethwatcher height=8628744 caller=ethclient.go:182
[DBUG][2018-09-06 20:46:49.004] ethwatcher received block                module=ethwatcher height=8628745 caller=ethclient.go:182
[DBUG][2018-09-06 20:47:01.670] ethwatcher received block                module=ethwatcher height=8628746 caller=ethclient.go:182
[DBUG][2018-09-06 20:47:04.456] ethwatcher received block                module=ethwatcher height=8628747 caller=ethclient.go:182
[DBUG][2018-09-06 20:47:13.096] ethwatcher received block                module=ethwatcher height=8628748 caller=ethclient.go:182
[DBUG][2018-09-06 20:47:25.553] ethwatcher received block                module=ethwatcher height=8628750 caller=ethclient.go:182
[DBUG][2018-09-06 20:47:38.406] ethwatcher received block                module=ethwatcher height=8628751 caller=ethclient.go:182
[DBUG][2018-09-06 20:47:40.476] ethwatcher received block                module=ethwatcher height=8628752 caller=ethclient.go:182
[DBUG][2018-09-06 20:47:48.718] ethwatcher received block                module=ethwatcher height=8628753 caller=ethclient.go:182
[DBUG][2018-09-06 20:47:56.306] ethwatcher received block                module=ethwatcher height=8628754 caller=ethclient.go:182
[DBUG][2018-09-06 20:48:02.304] ethwatcher received block                module=ethwatcher height=8628755 caller=ethclient.go:182
```

**Comment by Tbaut** [comment] 2018-09-06 14:54
This is a duplicate of https://github.com/paritytech/parity-ethereum/issues/9320. Please subscribe to this issue to get updates.

**Closed by Tbaut** 2018-09-06 14:54 UTC
