### ISSUE TITLE
Make Parity work with Remix

### ISSUE THREAD

**Issue by folsen** [paritytech/parity-ethereum#8672] opened 2018-05-21 03:17 UTC
This is a broad issue that requires investigation, but there are a couple of RPC calls that remix uses that Parity doesn't have (as reported in earlier issues), and sometimes there appears issues like https://github.com/paritytech/parity/issues/7813 that are failures of doing certain actions in remix.

Solving this issue probably includes getting in touch with the people working on remix to find out what would make parity a great backend for remix.

To Do:

* [ ] align the vmTrace output of the trace_replayTransaction call with Geths debug_traceTransaction
* ... definitely more, needs investigation

**Comment by MicahZoltu** [comment] 2018-06-05 10:20
Possibly duplicate of https://github.com/paritytech/parity/issues/5727

**Comment by Tbaut** [comment] 2018-11-14 15:34
Closing (it's indeed a duplicate)

**Closed by Tbaut** 2018-11-14 15:34 UTC
Labels: F8-enhancement 🎊, M4-core ⛓, P7-nicetohave 🐕, Q5-substantial 📓
