### ISSUE TITLE
Panic during stack allocation 

### ISSUE THREAD

**Issue by cxd1995** [paritytech/parity-ethereum#10633] opened 2019-05-07 03:13 UTC
Basic information about Parity
- **Parity Ethereum version**: 2.4.5-stable
- **Operating system**:  Linux
- **Installation**:  built from source
- **Fully synchronized**:  yes
- **Network**: ethereum 
- **Restarted**: yes

We encounter the problem several times this week. Note that silimar questions have been mentioned before including issue #8667 & #8444. But the bug has not been solved yet. We are sure that the memory of our server is plenty. Although the problem could also be alleviated by restarting parity rpc, this is not a permanent solution. 
The information about the bug is presented below.
![image](https://user-images.githubusercontent.com/45622921/57269065-8fc73000-70b8-11e9-8195-85b285147d78.png)

![image](https://user-images.githubusercontent.com/45622921/57269071-95247a80-70b8-11e9-89aa-6e31601b55b4.png)

**Comment by joshua-mir** [comment] 2019-05-08 22:57
The first screenshot is caused by db corruption due to a bad shutdown of your node or otherwise hardware failure. The second error is very unfamiliar to me though - and is likely what caused the first screenshot if I understand correctly?

**Comment by dvdplm** [comment] 2019-06-04 12:20
`failed to allocate an alternative stack` indicates a memory allocation failure – maybe this is a sign of the server running out of memory?

**Comment by debris** [comment] 2019-06-26 09:50
> `failed to allocate an alternative stack` indicates a memory allocation failure – maybe this is a sign of the server running out of memory?

I think so as well. There is nothing we can do about it as it is not a bug in the codebase. I'm closing the issue

**Closed by debris** 2019-06-26 09:50 UTC
Labels: F1-panic 🔨, M4-core ⛓, P5-sometimesoon 🌲
