### ISSUE TITLE
Crash report v2.0.1-beta

### ISSUE THREAD

**Issue by tjayrush** [paritytech/parity-ethereum#9388] opened 2018-08-21 12:49 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 0.0.0

linux:(develop)@./build:jrush>$ parity --version
Parity
  version Parity-Ethereum/v2.0.1-beta-e7dc0be-20180726/x86_64-linux-gnu/rustc1.27.2
Copyright 2015, 2016, 2017, 2018 Parity Technologies (UK) Ltd
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

By Wood/Paronyan/Kotewicz/Drwięga/Volf
   Habermeier/Czaban/Greeff/Gotchac/Redmann

> - **Which operating system?**: Windows / MacOS / Linux

MacOS

> - **How installed?**: via installer / homebrew / binaries / from source

installer script

> - **Are you fully synchronized?**: no / yes

yes, for many months, no problems

> - **Which network are you connected to?**: ethereum / ropsten / kovan / ...

mainnet

> - **Did you try to restart the node?**: no / yes

Not yet, but it told me to report anyway. Will report back after reboot

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._

    Expected:       Not to crash
    Actual:            Crash

2018-08-21 04:26:15  Imported #6186329 0xee6d…a5bf (206 txs, 7.96 Mgas, 327 ms, 28.94 KiB)
2018-08-21 04:26:21  Imported #6186331 0x57a6…d465 (24 txs, 7.99 Mgas, 666 ms, 17.49 KiB) + another 1 block(s) containing 37 tx(s)
2018-08-21 04:26:31  Imported #6186332 0x923c…5d1f (66 txs, 2.36 Mgas, 84 ms, 9.79 KiB)
2018-08-21 04:26:31  DB corrupted: Corruption: block checksum mismatch: expected 2179978558, got 265925217  in /media/jrush/6cb7072d-c89f-4377-ab4c-927e15bc721e/ethereum/db/906a34e69aec8c0d/archive/db/3052487.sst offset 6583776 size 16218. Repair will be triggered on next restart

====================

stack backtrace:
   0:     0x55b61261bf5c - <no info>
   1:     0x55b61261b522 - <no info>
   2:     0x55b61261aa7a - <no info>
   3:     0x55b6112023d5 - <no info>
   4:     0x55b612678005 - <no info>
   5:     0x55b612677b4c - <no info>
   6:     0x55b612677b11 - <no info>
   7:     0x55b6126dd5a2 - <no info>
   8:     0x55b611ea4e88 - <no info>
   9:     0x55b611c5c878 - <no info>
  10:     0x55b61199ca6b - <no info>
  11:     0x55b611dae180 - <no info>
  12:     0x55b611cfb7a7 - <no info>
  13:     0x55b611ce5a45 - <no info>
  14:     0x55b611d071bd - <no info>
  15:     0x55b6126a32d9 - <no info>
  16:     0x55b611dabaef - <no info>
  17:     0x55b6126946fa - <no info>
  18:     0x55b612678615 - <no info>
  19:     0x7f0f956fa6b9 - <no info>
  20:     0x7f0f9521a41c - <no info>
  21:                0x0 - <no info>

Thread 'Verifier #4' panicked at 'DB flush failed.: Custom { kind: Other, error: StringError("Corruption: block checksum mismatch: expected 2179978558, got 265925217  in /media/jrush/6cb7072d-c89f-4377-ab4c-927e15bc721e/ethereum/db/906a34e69aec8c0d/archive/db/3052487.sst offset 6583776 size 16218") }', libcore/result.rs:945

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

2018-08-21 04:26:31  Finishing work, please wait...
2018-08-21 04:26:31  DB corrupted: Corruption: block checksum mismatch: expected 2179978558, got 265925217  in /media/jrush/6cb7072d-c89f-4377-ab4c-927e15bc721e/ethereum/db/906a34e69aec8c0d/archive/db/3052487.sst offset 6583776 size 16218. Repair will be triggered on next restart
2018-08-21 04:26:32  DB corrupted: Corruption: block checksum mismatch: expected 2179978558, got 265925217  in /media/jrush/6cb7072d-c89f-4377-ab4c-927e15bc721e/ethereum/db/906a34e69aec8c0d/archive/db/3052487.sst offset 6583776 size 16218. Repair will be triggered on next restart

====================

stack backtrace:
   0:     0x55b61261bf5c - <no info>
   1:     0x55b61261b522 - <no info>
   2:     0x55b61261aa7a - <no info>
   3:     0x55b6112023d5 - <no info>
   4:     0x55b612678005 - <no info>
   5:     0x55b612677b4c - <no info>
   6:     0x55b612677b11 - <no info>
   7:     0x55b6126dd5a2 - <no info>
   8:     0x55b61107e77a - <no info>
   9:     0x55b61109f552 - <no info>
  10:     0x55b610fbd8f0 - <no info>
  11:     0x55b610fbe783 - <no info>
  12:     0x55b6119f550a - <no info>
  13:     0x55b61162b4da - <no info>
  14:     0x55b61163c874 - <no info>
  15:     0x55b6116225bf - <no info>
  16:     0x55b61152b343 - <no info>
  17:     0x55b611223d4a - <no info>
  18:     0x55b61121a5ac - <no info>
  19:     0x55b61122306a - <no info>
  20:     0x55b611267b56 - <no info>
  21:     0x55b61121bc84 - <no info>
  22:     0x55b611075f5b - <no info>
  23:     0x55b612344081 - <no info>
  24:     0x55b6123367ed - <no info>
  25:     0x55b612336294 - <no info>
  26:     0x55b61233b70b - <no info>
  27:     0x55b6126a32d9 - <no info>
  28:     0x55b612342fdc - <no info>
  29:     0x55b6126946fa - <no info>
  30:     0x55b612678615 - <no info>
  31:     0x7f0f956fa6b9 - <no info>
  32:     0x7f0f9521a41c - <no info>
  33:                0x0 - <no info>

Thread '<unnamed>' panicked at 'Propagating verifier thread panic on shutdown: Any', libcore/result.rs:945

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

**Comment by Tbaut** [comment] 2018-08-21 13:59
Thanks for the report, this is a duplicate of https://github.com/paritytech/parity-ethereum/issues/9376

**Closed by Tbaut** 2018-08-21 13:59 UTC
