### ISSUE TITLE
eth_getTrasnactionReceipt doesnt show gasUsed

### ISSUE THREAD

**Issue by gnd** [paritytech/parity-ethereum#10265] opened 2019-01-30 13:37 UTC
I am running `Parity-Ethereum//v2.3.0-beta-10657d9-20190115/x86_64-linux-gnu/rustc1.31.1` on a `Debian 9 kernel 4.15.0-43-generic #46~16.04.1-Ubuntu.`

This is my config:
```
[parity]
mode = "active"
light = true

[footprint]
tracing = "off"
pruning = "fast"
fat_db = "off"

[misc]
log_file = "/var/log/parity"
```

When I run a `eth_getTransactionReceipt` i am not shown the gasUsed values. For example for transaction hash 

> 0xd0f4f57659b8f3e3436e81cdbafd1a33f4bdee8031e2337f55af72c5d3b9c101

 I am shown this:

`{"jsonrpc":"2.0","result":{"blockHash":"0x0ea1675e1e80885a74940ae8ea728db1fe007e637f847a792ca17f7c1d6e35ad","blockNumber":"0x6d1568","contractAddress":null,"cumulativeGasUsed":"0x15245","from":null,"gasUsed":null,"logs":[{"address":"0x3fbe1f8fc5ddb27d428aa60f661eaaab0d2000ce","blockHash":null,"blockNumber":null,"data":"0x0000000000000000000000008fa8af91c675452200e49b4683a33ca2e1a34e420000000000000000000000007c79db6fb5529c2c05919da2cac1735956f8cfb2d6f2301c199daa8f8de7b46db0ee25bd271f1b9df15fa886b11d1c3937571bbc000000000000000000000000891aab0ec0a2c22a2398d48b5b520f93e25762df000000000000000000000000000000000000000000000002b5e3af16b188000000000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000000","logIndex":null,"removed":false,"topics":["0x59bed9ab5d78073465dd642a9e3e76dfdb7d53bcae9d09df7d0b8f5234d5a806"],"transactionHash":null,"transactionIndex":null,"transactionLogIndex":null,"type":"pending"}],"logsBloom":"0x00000800000000000000000000000000000000000400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000","root":null,"status":"0x1","to":null,"transactionHash":"0xd0f4f57659b8f3e3436e81cdbafd1a33f4bdee8031e2337f55af72c5d3b9c101","transactionIndex":"0x1"},"id":67}`

Obviously, when checking the TX on [etherchain](https://www.etherchain.org/tx/0xd0f4f57659b8f3e3436e81cdbafd1a33f4bdee8031e2337f55af72c5d3b9c101) the gasUsed is not NULL. Is this caused by the "light" mode ? Thanks for any answers.

**Comment by joshua-mir** [comment] 2019-01-30 13:40
Yes, this is caused either by light mode, (if you are grabbing a receipt from a transaction you've made locally) or if you call eth_gettransactionreceipt before the transaction has been confirmed.

**Comment by gnd** [comment] 2019-01-30 13:42
Its is not my transaction. I need to pull all transactions from the last N blocks, and check how many fees have been paid. So are you suggesting I should not use Light mode for that ?

**Comment by gnd** [comment] 2019-01-30 13:47
Thanks! My N is a really small number. I am a bit confused now. According to you it should work with my current setup ? Yet, it doesnt - see the example above - i get gasUsed being NULL for any transacton I try.

**Comment by joshua-mir** [comment] 2019-01-30 15:15
Just looking through the code I'm personally uncertain whether this is intended or not.

**Comment by joshua-mir** [comment] 2019-05-28 15:13
Closing this in favor of #10697

**Closed by joshua-mir** 2019-05-28 15:13 UTC
Labels: F3-annoyance 💩
