### ISSUE TITLE
unable to get mut ref for engine for shutdown

### ISSUE THREAD

**Issue by streetcrypto7** [paritytech/parity-ethereum#10937] opened 2019-08-02 14:24 UTC
- **Parity Ethereum version**: 2.5.5
- **Operating system**: Linux
- **Installation**: release file
- **Fully synchronized**: no
- **Network**: ethereum / ropsten
- **Restarted**: no

Parity slow stop with error message: `unable to get mut ref for engine for shutdown`

Full log from serviced

```
Aug 02 23:22:21 parity[6635]: 2019-08-02 23:22:21  Syncing #1748024 0x18ff…46f4    26.52 blk/s  354.0 tx/s   22.9 Mgas/s      0+ 7184 Qed  #1755208   43/50 peers    275 MiB chain  167 MiB db   42 MiB queue   51 MiB sync  RPC:  0 conn,    0 req/s,    0 µs
Aug 02 23:22:22 parity[6635]: 2019-08-02 23:22:22  Syncing #1748304 0xff17…91c2   160.73 blk/s 1176.2 tx/s   43.5 Mgas/s      0+ 6896 Qed  #1755208   43/50 peers    275 MiB chain  167 MiB db   40 MiB queue   51 MiB sync  RPC:  0 conn,    0 req/s,    0 µs
Aug 02 23:22:36 parity[6635]: 2019-08-02 23:22:36  Syncing #1748828 0xc254…50c7    39.31 blk/s  221.4 tx/s    9.5 Mgas/s      0+ 7523 Qed  #1756351   43/50 peers    276 MiB chain  167 MiB db   44 MiB queue   51 MiB sync  RPC:  0 conn,    0 req/s,    0 µs
Aug 02 23:22:36 parity[6635]: 2019-08-02 23:22:36  Syncing #1748828 0xc254…50c7   111.11 blk/s 1027.8 tx/s   53.1 Mgas/s      0+ 7523 Qed  #1756351   43/50 peers    276 MiB chain  167 MiB db   44 MiB queue   51 MiB sync  RPC:  0 conn,    0 req/s,    0 µs
Aug 02 23:22:37 parity[6635]: 2019-08-02 23:22:37  Syncing #1749255 0xd932…24b4   245.53 blk/s 1551.0 tx/s   89.0 Mgas/s      0+ 7091 Qed  #1756351   43/50 peers    276 MiB chain  167 MiB db   41 MiB queue   51 MiB sync  RPC:  0 conn,    0 req/s,    0 µs
Aug 02 23:22:41 systemd[1]: Stopping Parity Node Daemon...
Aug 02 23:22:41 parity[6635]: 2019-08-02 23:22:41  Finishing work, please wait...
Aug 02 23:22:41 parity[6635]: 2019-08-02 23:22:41  unable to get mut ref for engine for shutdown.
Aug 02 23:22:42 systemd[1]: Stopped Parity Node Daemon.
Aug 02 23:22:42 systemd[1]: Started Parity Node Daemon.
Aug 02 23:22:42 parity[8056]: 2019-08-02 23:22:42  Starting Parity-Ethereum/v2.5.5-stable-3ebc769-20190708/x86_64-linux-gnu/rustc1.36.0
Aug 02 23:22:42 parity[8056]: 2019-08-02 23:22:42  State DB configuration: fast
Aug 02 23:22:42 parity[8056]: 2019-08-02 23:22:42  Operating mode: active
```

**Comment by Genysys** [comment] 2019-08-02 15:16
do you have logs from when the service failed? i think `journctl -r | grep parity`  might be worth looking at

**Comment by seunlanlege** [comment] 2019-08-05 16:22
Previous occurrences of this error have been caused by your machine running out of disk space, can you confirm that's not the case?

**Comment by streetcrypto7** [comment] 2019-08-05 17:15
@seunlanlege Well I can say that is not a case, parity consumes about 50GB while I have 500GB ssd mounted.

**Comment by dvdplm** [comment] 2019-08-06 05:48
@streetcrypto7 you write that Parity is slow to stop. Looking at the log timestamps however seems to indicate that systemd takes 1 second to restart the node:

```
23:22:41 systemd[1]: Stopping Parity
…
23:22:42 systemd[1]: Stopped Parity
```

That seems normal or even faster than normal to me.

**Comment by niklasad1** [comment] 2019-09-13 12:56
`unable to get mut ref for engine for shutdown` is not possible on `latest master` can we close this @dvdplm ?

**Closed** 2019-09-13 13:28 UTC
Labels: F3-annoyance 💩, M4-core ⛓
