### ISSUE TITLE
Aborting seal generation for invalid step: 1529909210 > 764954879

### ISSUE THREAD

**Issue by zhjgit** [paritytech/parity-ethereum#8970] opened 2018-06-25 07:26 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: v1.10.4-stable
> - **Which operating system?**:Linux
> - **How installed?**: binaries 
> - **Are you fully synchronized?**: yes
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

_Your issue description goes here below. Try to include **actual** vs. **expected behavior** and **steps to reproduce** the issue._
----------------------
parity node update block time,restart parity node ,
this is a problem : Aborting seal generation for invalid step: 1529909210 > 764954879,
how should i solve it ?

**Comment by 5chdn** [comment] 2018-06-25 07:33
Hello. Please upgrade to 1.10.7 or 1.11.4.

Also, please share the full log that precedes the error message you pasted above. What does your configuration look like?

**Comment by jchen86** [comment] 2018-07-17 08:55
Hi,

I'm having the same problem on 1.11.5, local network of 3 nodes, PoA engine. 

This error doesn't seem to be recoverable, I had to wipe my local data to get my dev environment running again. I don't have the server logs at the moment but this is the client side error I got when when I tried to send a transaction over WebSocket:
`Error: Returned error: There are too many transactions in the queue. Your transaction was dropped due to limit. Try increasing the fee`

Will provide server log if if I can reproduce this.

Thanks.

**Comment by yamarkz** [comment] 2018-07-25 03:37
I'm having the same problem

**Comment by andresilva** [comment] 2018-07-27 10:17
Could you explain what you changed for this to happen? If you tried to change the step duration this is expected. You have to restart a new chain if you want to change any option in the chainspec that doesn't have a transition flag.

**Comment by andresilva** [comment] 2018-08-29 17:35
I just re-read the issue description:

> parity node update block time,restart parity node ,

You can't update the step duration on a live chain, this is expected behavior. Closing

**Closed by andresilva** 2018-08-29 17:35 UTC
Labels: M4-core, Z9-invalid
