### ISSUE TITLE
Private network: Sending ether from a preexisting account

### ISSUE THREAD

**Issue by BlockchainDieter** [paritytech/parity-ethereum#9913] opened 2018-11-13 15:12 UTC
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.0.9
- **Operating system**:  Linux
- **Installation**: Docker
- **Fully synchronized**: no 
- **Network**: private
- **Restarted**:  yes

I am currently experimenting with Ethereum and trying to set up a private blockchain using parity. For this, I created the genesis file below. I then booted two parity nodes with the following command line, using parity version `v2.0.9`: 

    --jsonrpc-interface=all --port 31337 --jsonrpc-port 8539 --chain /chainspec/parity.json --jsonrpc-apis all -l rpc=trace
    --jsonrpc-interface=all --port 31338 --jsonrpc-port 8540 --chain /chainspec/parity.json --jsonrpc-apis all -l rpc=trace

Now I connect the two peers using the `parity_enode` and the `parity_addReservedPeer` rpc-call. This works fine. But when I try to create a new account and transfer Ether from one of the preexisting accounts, I get an error message. Here are the rpc calls I use:

    address = parity_newAccountFromPhrase(params=["test", "test"])
    personal_sendTransaction(params=[{"from": "0x00a429c0648769a73afac7f9381e08fb43dbea72", "to": address, "value": "0x10", "gas": "0x76c0"}, ""])

Which returns:
`  {"jsonrpc":"2.0","error":{"code":-32021,"message":"Account password is invalid or account does not exist.","data":"SStore(InvalidAccount)"},"id":1}`

What am I missing here? As far as I understand, the preexisting account should have an empty string as password - so why is this not working?

My genesis file:

    {
    "name": "CrossClient",asdfas
    "dataDir": "CrossClient",
    "engine": {
        "Ethash": {
            "params": {
                "minimumDifficulty": "0x020000",
                "difficultyBoundDivisor": "0x0800",
                "durationLimit": "0x0d",
                "blockReward": "0x4563918244F40000",
                "homesteadTransition": 0,
                "eip150Transition": 0,
                "eip160Transition": 10,
                "eip161abcTransition": 10,
                "eip161dTransition": 10
            }
        }
    },
    "params": {
        "gasLimitBoundDivisor": "0x0400",
        "registrar": "0x81a4b044831c4f12ba601adb9274516939e9b8a2",
        "eip155Transition": 10,
        "accountStartNonce": "0x0",
        "maximumExtraDataSize": "0x20",
        "minGasLimit": "0x1388",
        "networkID" : "0x539"
    },
    "genesis": {
        "seal": {
            "ethereum": {
                "nonce": "0x0000000000000042",
                "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
            }
        },
        "difficulty": "0x10000",
        "author": "0x0000000000000000000000000000000000000000",
        "timestamp": "0x00",
        "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
        "extraData": "0x3535353535353535353535353535353535353535353535353535353535353535",
        "gasLimit": "0x1000000"
    },
    "accounts": {
        "0000000000000000000000000000000000000001": { "balance": "1", "nonce": "0", "builtin": { "name": "ecrecover", "pricing": { "linear": { "base": 3000, "word": 0 } } } },
        "0000000000000000000000000000000000000002": { "balance": "1", "nonce": "0", "builtin": { "name": "sha256", "pricing": { "linear": { "base": 60, "word": 12 } } } },
        "0000000000000000000000000000000000000003": { "balance": "1", "nonce": "0", "builtin": { "name": "ripemd160", "pricing": { "linear": { "base": 600, "word": 120 } } } },
        "0000000000000000000000000000000000000004": { "balance": "1", "nonce": "0", "builtin": { "name": "identity", "pricing": { "linear": { "base": 15, "word": 3 } } } },
        "0x00a429c0648769a73afac7f9381e08fb43dbea72": { "balance": "1606938044258990275541962092341162602522202993782792835301376" },
        "0x00a329c0648769a73afac7f9381e08fb43dbea72": { "balance": "1606938044258990275541962092341162602522202993782792835301376" }
    }
    }

**Comment by joshua-mir** [comment] 2018-11-13 15:17
Likely a duplicate of https://github.com/paritytech/parity-ethereum/issues/9737 :sweat_smile: please check that issue out for a workaround

**Comment by BlockchainDieter** [comment] 2018-11-13 16:20
Thanks for the advice. I tried with the following config file:

```
# This config should be placed in following path:
#   ~/.local/share/io.parity.ethereum/config.toml

[parity]
# Local Development Chain
chain = "/chainspec/parity.json"

[rpc]
port = 8539 #default http port for RPC
apis = ["all"] # to access dedicated methods

[network]
port = 31337

[account]
# From: [0x00a329c0648769a73afac7f9381e08fb43dbea72] you'll be able to send transactions without password.
unlock = ["0x00a329c0648769a73afac7f9381e08fb43dbea72"]
# File at ./empty_pass should contain a single empty line. (password is an empty string)
password = ["/config/empty.txt"]
```

And got the following output, even after restarting:

```

parity@2f3fa8e63a80:~$ parity -c /config/parity_config.toml                                                                                 
Loading config file from /config/parity_config.toml
2018-11-13 16:19:42 UTC Starting Parity-Ethereum/v2.0.9-stable-09f7757-20181028/x86_64-linux-gnu/rustc1.30.0
2018-11-13 16:19:42 UTC Keys path /home/parity/.local/share/io.parity.ethereum/keys/CrossClient
2018-11-13 16:19:42 UTC DB path /home/parity/.local/share/io.parity.ethereum/chains/CrossClient/db/02c68145b8bcf291
2018-11-13 16:19:42 UTC State DB configuration: fast
2018-11-13 16:19:42 UTC Operating mode: active
Account 0x00a3…ea72 not found for the current chain. You can create an account via RPC, UI or `parity account new --chain /chainspec/parity.json --keys-path /home/parity/.local/share/io.parity.ethereum/keys`.
parity@2f3fa8e63a80:~$ parity -c /config/parity_config.toml 
Loading config file from /config/parity_config.toml
2018-11-13 16:19:43 UTC Starting Parity-Ethereum/v2.0.9-stable-09f7757-20181028/x86_64-linux-gnu/rustc1.30.0
2018-11-13 16:19:43 UTC Keys path /home/parity/.local/share/io.parity.ethereum/keys/CrossClient
2018-11-13 16:19:43 UTC DB path /home/parity/.local/share/io.parity.ethereum/chains/CrossClient/db/02c68145b8bcf291
2018-11-13 16:19:43 UTC State DB configuration: fast
2018-11-13 16:19:43 UTC Operating mode: active
Account 0x00a3…ea72 not found for the current chain. You can create an account via RPC, UI or `parity account new --chain /chainspec/parity.json --keys-path /home/parity/.local/share/io.parity.ethereum/keys`.
parity@2f3fa8e63a80:~$ 

```

**Comment by joshua-mir** [comment] 2018-11-13 16:25
Sorry, I failed to notice you were using a custom chain. The "default account" only exists when you use the `dev` chain. It's easy to create because it's the account you get when restoring from an empty seed phrase. You can use https://wiki.parity.io/JSONRPC-parity_accounts-module#parity_newaccountfromphrase to add it to your local accounts as well, or just change your chain spec to use an account your node owns instead of the default.

**Closed by joshua-mir** 2018-11-13 16:25 UTC
Labels: F3-annoyance 💩, Z1-question 🙋‍♀️

**Comment by BlockchainDieter** [comment] 2018-11-13 17:06
Thank you very much for your response - very helpful. You mentioned "changing my chain spec to use an account your node owns instead of default". I thought I already did that by including additional accounts in the genesis file. Is that no sufficient?

```
"accounts": {
    "0000000000000000000000000000000000000001": { "balance": "1", "nonce": "0", "builtin": { "name": "ecrecover", "pricing": { "linear": { "base": 3000, "word": 0 } } } },
    "0000000000000000000000000000000000000002": { "balance": "1", "nonce": "0", "builtin": { "name": "sha256", "pricing": { "linear": { "base": 60, "word": 12 } } } },
    "0000000000000000000000000000000000000003": { "balance": "1", "nonce": "0", "builtin": { "name": "ripemd160", "pricing": { "linear": { "base": 600, "word": 120 } } } },
    "0000000000000000000000000000000000000004": { "balance": "1", "nonce": "0", "builtin": { "name": "identity", "pricing": { "linear": { "base": 15, "word": 3 } } } },
    "0x00a429c0648769a73afac7f9381e08fb43dbea72": { "balance": "1606938044258990275541962092341162602522202993782792835301376" },
    "0x00a329c0648769a73afac7f9381e08fb43dbea72": { "balance": "1606938044258990275541962092341162602522202993782792835301376" }
}
```

**Comment by joshua-mir** [comment] 2018-11-13 17:07
That's fine (but it won't add those accounts to your node, you still need to do that yourself)

**Comment by BlockchainDieter** [comment] 2018-11-13 17:24
Last question, I am really sorry:

How do I add accounts to my node?

**Comment by BlockchainDieter** [comment] 2018-11-14 00:01
The problem with the newAccount methods is that the new accounts do not have balance already. Is there any way to have a custom genesis file and also have preexisting accounts with non zero balance from which I can make transfers?
