### ISSUE TITLE
panicked at 'called `Result::unwrap()`

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-ethereum#10177] opened 2019-01-14 10:27 UTC
_Before filing a new issue, please **provide the following information**._

- **Parity Ethereum version**: 2.2.5 & 2.2.6
- **Operating system**: Linux
- **Installation**: one-line installer
- **Fully synchronized**: no
- **Network**: kovan --light
- **Restarted**: yes

When exiting parity `ctrl+c` this happened. I can't reproduce each time. My light node was syncing for a couple seconds as you can see.

```
parity --chain kovan --light        
2019-01-14 11:17:38  Starting Parity-Ethereum/v2.2.5-beta-7fbcdfe-20181213/x86_64-linux-gnu/rustc1.31.0
2019-01-14 11:17:38  Keys path /home/thib/.local/share/io.parity.ethereum/keys/kovan
2019-01-14 11:17:38  DB path /home/thib/.local/share/io.parity.ethereum/chains_light/kovan/db/9bf388941c25ea98
2019-01-14 11:17:38  Running in experimental Light Client mode.
2019-01-14 11:17:39  Inserting hardcoded block #9363457 in chain
2019-01-14 11:17:39  Public node URL: enode://8c820b97320e978b841fe62fed9a6ac2baca0ff59abe40460d2fba7e062ebe3ec4ad48c815a9656d9b26ba3f593640bb4ac4347fcbf0362637770d724b96d7c2@192.168.1.163:30303
2019-01-14 11:17:39  Debug API is not available in light client mode.
2019-01-14 11:17:39  Debug API is not available in light client mode.
2019-01-14 11:17:44  Syncing #9366017 0x08f4…e606   512.0 hdr/s      0+    0 Qed  13/50 peers   2 MiB cache 0 bytes queue  RPC:  1 conn,    1 req/s,   70 µs
2019-01-14 11:17:49  Syncing #9371817 0x618b…fb06  1160.0 hdr/s      0+ 7422 Qed  12/50 peers   5 MiB cache 6 MiB queue  RPC:  1 conn,    1 req/s,   70 µs
2019-01-14 11:17:54  Syncing #9387322 0xad0a…a91b  3101.0 hdr/s      0+23678 Qed  14/50 peers   10 MiB cache 18 MiB queue  RPC:  1 conn,    2 req/s,   68 µs
2019-01-14 11:17:59  Syncing #9402919 0x1ff4…b65b  3119.4 hdr/s      0+25599 Qed  16/50 peers   10 MiB cache 20 MiB queue  RPC:  1 conn,    1 req/s,   66 µs
2019-01-14 11:18:04  Syncing #9418386 0xbfa2…11c8  3093.4 hdr/s      0+18943 Qed  14/50 peers   10 MiB cache 14 MiB queue  RPC:  0 conn,    1 req/s,   60 µs
^C2019-01-14 11:18:09  Syncing #9434995 0x9ba4…78d8  3321.8 hdr/s      0+24575 Qed  15/50 peers   10 MiB cache 19 MiB queue  RPC:  1 conn,    1 req/s,   62 µs


====================

stack backtrace:
   0:     0x5591ba696e1d - <no info>
   1:     0x5591ba696032 - <no info>
   2:     0x5591ba6960a9 - <no info>
   3:     0x5591ba6951e6 - <no info>
   4:     0x5591b8e7d7e8 - <no info>
   5:     0x5591ba70f396 - <no info>
   6:     0x5591ba70eee1 - <no info>
   7:     0x5591ba70edc5 - <no info>
   8:     0x5591ba75895c - <no info>
   9:     0x5591b91e6cdc - <no info>
  10:     0x5591b95b2559 - <no info>
  11:     0x5591b95853f8 - <no info>
  12:     0x5591b9554338 - <no info>
  13:     0x5591b92eda81 - <no info>
  14:     0x5591b95a1e6e - <no info>
  15:     0x5591b923c772 - <no info>
  16:     0x5591b9162ed6 - <no info>
  17:     0x5591ba7217f9 - <no info>
  18:     0x5591b9185617 - <no info>
  19:     0x5591ba70b82d - <no info>
  20:     0x5591ba6f6125 - <no info>
  21:     0x7f05d45a36b9 - <no info>
  22:     0x7f05d40c341c - <no info>
  23:                0x0 - <no info>

Thread 'IO Worker #1' panicked at 'called `Result::unwrap()` on an `Err` value: SpawnError { is_shutdown: true }', libcore/result.rs:1009

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new



====================

stack backtrace:
   0:     0x5591ba696e1d - <no info>
   1:     0x5591ba696032 - <no info>
   2:     0x5591ba6960a9 - <no info>
   3:     0x5591ba6951e6 - <no info>
   4:     0x5591b8e7d7e8 - <no info>
   5:     0x5591ba70f396 - <no info>
   6:     0x5591ba70eee1 - <no info>
   7:     0x5591ba70edc5 - <no info>
   8:     0x5591ba75895c - <no info>
   9:     0x5591b91e6cdc - <no info>
  10:     0x5591b95b2559 - <no info>
  11:     0x5591b95853f8 - <no info>
  12:     0x5591b9554338 - <no info>
  13:     0x5591b92eda81 - <no info>
  14:     0x5591b95a1e6e - <no info>
  15:     0x5591b923c772 - <no info>
  16:     0x5591b9162ed6 - <no info>
  17:     0x5591ba7217f9 - <no info>
  18:     0x5591b9185617 - <no info>
  19:     0x5591ba70b82d - <no info>
  20:     0x5591ba6f6125 - <no info>
  21:     0x7f05d45a36b9 - <no info>
  22:     0x7f05d40c341c - <no info>
  23:                0x0 - <no info>

Thread 'IO Worker #2' panicked at 'called `Result::unwrap()` on an `Err` value: SpawnError { is_shutdown: true }', libcore/result.rs:1009

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new
```

**Comment by niklasad1** [comment] 2019-01-14 10:48
Thanks @Tbaut 

This is related to change of using `tokio executor` in the I/O workers instead of spawning raw threads. The cause is a `shutdown call` on a already shutdown worker, https://tokio-rs.github.io/tokio/tokio_executor/struct.SpawnError.html

/cc @ngotchac you have spend some time on this, is it related or solved by #10144?

**Comment by ngotchac** [comment] 2019-01-14 11:03
@niklasad1 I've never seen this so I don't think it's related, nor fixed by this PR :/

**Comment by Tbaut** [comment] 2019-01-14 15:51
Here is the trace with master:
```
stack backtrace:
   0:     0x560bdaaf5e7d - backtrace::backtrace::trace::h9cba09a270894780
   1:     0x560bdaaf5092 - <backtrace::capture::Backtrace as core::default::Default>::default::h2d345f667ea34cba
   2:     0x560bdaaf5109 - backtrace::capture::Backtrace::new::hf3eec8642311a0b2
   3:     0x560bdaaf4246 - panic_hook::gen_panic_msg::h1b22ef7225dcd8f5
   4:     0x560bd92aa218 - panic_hook::set_with::{{closure}}::hed20d4db8ab42113
   5:     0x560bdab6bff6 - std::panicking::rust_panic_with_hook::h71214e7ce0f7ac01
                        at libstd/panicking.rs:480
   6:     0x560bdab6bb41 - std::panicking::continue_panic_fmt::ha8b8442f4ea9bcac
                        at libstd/panicking.rs:390
   7:     0x560bdab6ba25 - rust_begin_unwind
                        at libstd/panicking.rs:325
   8:     0x560bdabb55bc - core::panicking::panic_fmt::h0c93626b89c38af6
                        at libcore/panicking.rs:77
   9:     0x560bd9a3f33c - core::result::unwrap_failed::hc11fd68322d246cc
  10:     0x560bd95f6c69 - parity_runtime::Executor::spawn::h18877ea7affef8a7
  11:     0x560bd9a4a658 - <parity_rpc::v1::impls::eth_pubsub::ChainNotificationHandler<C>>::notify::h34203e52d5560c31
  12:     0x560bd9a24568 - <parity_rpc::v1::impls::eth_pubsub::ChainNotificationHandler<C> as ethcore_light::client::LightChainNotify>::new_headers::h6ce9465d6a6d2087
  13:     0x560bd9762ec1 - <ethcore_light::client::Client<T>>::import_verified::h370e4ff3b3760e10
  14:     0x560bd97320fd - ethcore_io::worker::Worker::do_work::h496200ddd74ed78f
  15:     0x560bd96ba8ff - ethcore_io::worker::Worker::new::{{closure}}::{{closure}}::h429b31f0cff81876
  16:     0x560bd9711f6c - <futures::future::loop_fn::LoopFn<A, F> as futures::future::Future>::poll::h4386cdccb2406914
  17:     0x560bd9a4cdac - futures::task_impl::std::set::hc0895d23044b4dfd
  18:     0x560bd966a193 - <std::thread::local::LocalKey<T>>::with::ha451c4f3df2571a6
  19:     0x560bd99e8cb6 - <tokio_current_thread::Entered<'a, P>>::block_on::he4444519893fba38
  20:     0x560bd9668854 - <std::thread::local::LocalKey<T>>::with::h189ced58f1dbaa09
  21:     0x560bd9668e76 - <std::thread::local::LocalKey<T>>::with::h37f4292a95af40e8
  22:     0x560bd966ac64 - <std::thread::local::LocalKey<T>>::with::heca3b646a76b9d0d
  23:     0x560bd966a839 - <std::thread::local::LocalKey<T>>::with::he234953b28360cec
  24:     0x560bd982e325 - tokio::runtime::current_thread::runtime::Runtime::block_on::h590ffa9387141a20
  25:     0x560bd97ef7dc - tokio::runtime::current_thread::block_on_all::h7b138ebf018e2bb9
  26:     0x560bd975a764 - std::sys_common::backtrace::__rust_begin_short_backtrace::h94a80ddf9e25bc01
  27:     0x560bd95927d6 - std::panicking::try::do_call::h589185a6247d57a5
  28:     0x560bdab7e459 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:102
  29:     0x560bd95ae507 - <F as alloc::boxed::FnBox<A>>::call_box::hf7b6eaa94c445ac1
  30:     0x560bdab6848d - <alloc::boxed::Box<(dyn alloc::boxed::FnBox<A, Output=R> + 'a)> as core::ops::function::FnOnce<A>>::call_once::he3acfc8f1203786f
                        at liballoc/boxed.rs:682
                         - std::sys_common::thread::start_thread::h5213f803a61d7811
                        at libstd/sys_common/thread.rs:24
  31:     0x560bdab52d85 - std::sys::unix::thread::Thread::new::thread_start::he89121f566d2a8c7
                        at libstd/sys/unix/thread.rs:90
  32:     0x7fe1c04a46b9 - start_thread
  33:     0x7fe1bffc441c - clone
  34:                0x0 - <unknown>

Thread 'IO Worker #3' panicked at 'called `Result::unwrap()` on an `Err` value: SpawnError { is_shutdown: true }', libcore/result.rs:1009

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new

```

**Closed** 2019-01-15 08:14 UTC
Labels: F1-panic 🔨, M4-core ⛓
