### ISSUE TITLE
Error syncing ropsten node with parity

### ISSUE THREAD

**Issue by jatinshah** [paritytech/parity-ethereum#9246] opened 2018-07-29 06:46 UTC
> I'm running:
>
> - **Which Parity version?**: 2.0.0
> - **Which operating system?**: Linux
> - **How installed?**: via installer 
> - **Are you fully synchronized?**: no 
> - **Which network are you connected to?**:  ropsten 
> - **Did you try to restart the node?**: yes

Tried to sync a ropsten node with 'parity --pruning archive --tracing on --fat-db on  --chain=ropsten  --cache-size=2048 --db-compaction=ssd --mode=active' and got this error message

stack backtrace:
   0:     0x55fbc7d2364c - <no info>
   1:     0x55fbc7d22c12 - <no info>
   2:     0x55fbc7d2216a - <no info>
   3:     0x55fbc68aaa85 - <no info>
   4:     0x55fbc7d7ed55 - <no info>
   5:     0x55fbc7d4aa16 - <no info>
   6:     0x55fbc7d4a0dd - <no info>
   7:     0x55fbc7456cc5 - <no info>
   8:     0x55fbc7353284 - <no info>
   9:     0x55fbc7095a1b - <no info>
  10:     0x55fbc74b1880 - <no info>
  11:     0x55fbc73fefc7 - <no info>
  12:     0x55fbc73e8e25 - <no info>
  13:     0x55fbc740a8dd - <no info>
  14:     0x55fbc7daa199 - <no info>
  15:     0x55fbc74afa8f - <no info>
  16:     0x55fbc7d9b5ba - <no info>
  17:     0x55fbc7d7f365 - <no info>
  18:     0x7f9f87a856da - <no info>
  19:     0x7f9f8759688e - <no info>
  20:                0x0 - <no info>

Thread 'Verifier #1' panicked at 'assertion failed: rc == -1', util/journaldb/src/archivedb.rs:141

This is a bug. Please report it at:

    https://github.com/paritytech/parity/issues/new

2018-07-29 06:44:12 UTC Finishing work, please wait...
2018-07-29 06:44:12 UTC Block import failed for #13971 (0xc8d1…1eb0): Parent not found (0xc63a…56f2) 

====================

stack backtrace:
   0:     0x55fbc7d2364c - <no info>
   1:     0x55fbc7d22c12 - <no info>
   2:     0x55fbc7d2216a - <no info>
   3:     0x55fbc68aaa85 - <no info>
   4:     0x55fbc7d7ed55 - <no info>
   5:     0x55fbc7d7e89c - <no info>
   6:     0x55fbc7d7e861 - <no info>
   7:     0x55fbc7de4462 - <no info>
   8:     0x55fbc67044aa - <no info>
   9:     0x55fbc673c963 - <no info>
  10:     0x55fbc6842940 - <no info>
  11:     0x55fbc68431b3 - <no info>
  12:     0x55fbc6838235 - <no info>
  13:     0x55fbc664d2b2 - <no info>
  14:     0x55fbc68340fa - <no info>
  15:     0x55fbc6832df3 - <no info>
  16:     0x55fbc68316ba - <no info>
  17:     0x55fbc68989f6 - <no info>
  18:     0x55fbc682c504 - <no info>
  19:     0x55fbc66f594b - <no info>
  20:     0x55fbc7a4a331 - <no info>
  21:     0x55fbc7a3cd6d - <no info>
  22:     0x55fbc7a3c544 - <no info>
  23:     0x55fbc7a419bb - <no info>
  24:     0x55fbc7daa199 - <no info>
  25:     0x55fbc7a4928c - <no info>
  26:     0x55fbc7d9b5ba - <no info>
  27:     0x55fbc7d7f365 - <no info>
  28:     0x7f9f87a856da - <no info>
  29:     0x7f9f8759688e - <no info>
  30:                0x0 - <no info>

Thread '<unnamed>' panicked at 'Propagating verifier thread panic on shutdown: Any', libcore/result.rs:945

**Comment by Tbaut** [comment] 2018-07-30 08:39
Thanks for the report. This is a duplicate of https://github.com/paritytech/parity-ethereum/issues/9180, please comment in this issue.

**Closed by Tbaut** 2018-07-30 08:39 UTC
