### ISSUE TITLE
Parity after new stable update.

### ISSUE THREAD

**Issue by shouvik2016** [paritytech/parity-ethereum#10397] opened 2019-02-21 18:15 UTC
2019-02-21 18:13:32 UTC Syncing #7160660 0x44ce…2a1e     0.00 blk/s    0.0 tx/s    0.0 Mgas/s      0+    0 Qed  #7196122    9/25 peers      6 MiB chain   65 MiB db  0 bytes queue   17 MiB sync  RPC:  1 conn,    1 req/s,  930 µs

====================

stack backtrace:
   0:     0x55a6ca82e75d - <no info>
   1:     0x55a6ca82d882 - <no info>
   2:     0x55a6ca82ca36 - <no info>
   3:     0x55a6c90112d8 - <no info>
   4:     0x55a6ca8a0ff9 - <no info>
   5:     0x55a6ca8a0aa1 - <no info>
   6:     0x55a6ca8a0985 - <no info>
   7:     0x55a6ca8be5fc - <no info>
   8:     0x55a6ca8be672 - <no info>
   9:     0x55a6c9f5c831 - <no info>
  10:     0x55a6c9f5c0e5 - <no info>
  11:     0x55a6c9e6b75b - <no info>
  12:     0x55a6c9f537c1 - <no info>
  13:     0x55a6c9f3c06e - <no info>
  14:     0x55a6c9dfb371 - <no info>
  15:     0x55a6c9d1193d - <no info>
  16:     0x55a6c9a1afba - <no info>
  17:     0x55a6c9a0ec95 - <no info>
  18:     0x55a6c99f815f - <no info>
  19:     0x55a6c99f8586 - <no info>
  20:     0x55a6ca8b7aa9 - <no info>
  21:     0x55a6c99fde67 - <no info>
  22:     0x55a6ca8ab63d - <no info>
  23:     0x7f424a1366b9 - <no info>
  24:     0x7f4249c5641c - <no info>
  25:                0x0 - <no info>

Thread 'IO Worker #0' panicked at 'nonce will return Some when given BlockId::Latest. nonce was given BlockId::Latest. Therefore nonce has returned Some; qed', src/libcore/option.rs:1008

This is a bug. Please report it at:

    https://github.com/paritytech/parity-ethereum/issues/new

2019-02-21 18:13:39 UTC Finishing work, please wait...
2019-02-21 18:14:39 UTC Shutdown is taking longer than expected.

**Comment by joshua-mir** [comment] 2019-02-21 18:22
Duplicate of #10075

**Closed by joshua-mir** 2019-02-21 18:22 UTC
