### ISSUE TITLE
When sync to the highest block, parity stop syncing

### ISSUE THREAD

**Issue by gs201510** [paritytech/parity-ethereum#8689] opened 2018-05-23 07:17 UTC
_Before filing a new issue, please **provide the following information**._

> I'm running:
>
> - **Which Parity version?**: 1.12.0
> - **Which operating system?**: Ubuntu16.04
> - **How installed?**: from source
> - **Are you fully synchronized?**:  yes
> - **Which network are you connected to?**: ethereum 
> - **Did you try to restart the node?**: yes

I just run ./parity with no params.After syncing snapshot , it began to sync blocks. But when it comes to the newest block, it stop syncing.
```
2018-05-23 07:08:16 UTC Syncing #5661694 0x7d66…8395   3.23 blk/s  530.0 tx/s   23 Mgas/s      0+  125 Qed  #5661800   47/50 peers      7 MiB chain  126 MiB db   15 MiB queue  978 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2018-05-23 07:08:16 UTC Syncing #5661729 0xe529…d93d   2.50 blk/s  460.6 tx/s   18 Mgas/s      0+   89 Qed  #5661800   47/50 peers      7 MiB chain  124 MiB db   11 MiB queue  978 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2018-05-23 07:08:25 UTC Reorg to #5661755 0x147a…17d7 (0x44ea…f787 #5661753 0xc165…3c72 0x3e7c…d321)
2018-05-23 07:08:31 UTC Syncing #5661746 0x2464…4c77   3.27 blk/s  514.1 tx/s   24 Mgas/s      0+   75 Qed  #5661802   47/50 peers      6 MiB chain  126 MiB db    9 MiB queue  782 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2018-05-23 07:08:31 UTC Syncing #5661770 0x9df5…638c   2.88 blk/s  471.1 tx/s   21 Mgas/s      0+   43 Qed  #5661802   47/50 peers      6 MiB chain  130 MiB db    5 MiB queue  782 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2018-05-23 07:08:36 UTC Reorg to #5661784 0x0165…d643 (0xccb4…9922 #5661782 0x6567…093b 0x0215…1ba0)
2018-05-23 07:08:37 UTC Reorg to #5661785 0xef32…160d (0x0165…d643 0x0215…1ba0 #5661782 0x6567…093b 0xccb4…9922 0xf58a…d9d1)
2018-05-23 07:08:41 UTC Syncing #5661797 0x91aa…fd29   3.40 blk/s  529.0 tx/s   26 Mgas/s      0+    7 Qed  #5661802   11/50 peers      6 MiB chain  133 MiB db  941 KiB queue  782 KiB sync  RPC:  0 conn,    0 req/s,    0 µs
2018-05-23 07:08:42 UTC Reorg to #5661798 0xd7d9…6e27 (0x91aa…fd29 #5661796 0x4485…c295 0x67bb…9a98)
2018-05-23 07:08:45 UTC Imported #5661802 0x420a…0c63 (174 txs, 8.00 Mgas, 1166 ms, 27.13 KiB) + another 2 block(s) containing 370 tx(s)
```
stopped at `Imported #5661802 0x420a…0c63 (174 txs, 8.00 Mgas, 1166 ms, 27.13 KiB) + another 2 block(s) containing 370 tx(s)`

**Comment by gs201510** [comment] 2018-05-23 07:38
When I run parity with ./parity -l sync=trace, I saw it stop at here:

> 2018-05-23 07:25:06 UTC IO Worker #0 TRACE sync  peer 33 is not suitable for asking old blocks
2018-05-23 07:25:06 UTC IO Worker #0 TRACE sync  Deactivating peer 33
2018-05-23 07:25:06 UTC IO Worker #0 TRACE sync  Syncing with peers: 6 active, 13 confirmed, 16 total
2018-05-23 07:25:06 UTC IO Worker #0 TRACE sync  Skipping busy peer 37
2018-05-23 07:25:06 UTC IO Worker #0 TRACE sync  Skipping busy peer 1
2018-05-23 07:25:06 UTC IO Worker #0 TRACE sync  Skipping busy peer 17
2018-05-23 07:25:06 UTC IO Worker #3 DEBUG sync  4 -> Dispatching packet: 2
2018-05-23 07:25:06 UTC IO Worker #3 TRACE sync  04 -> Transactions (1 entries)
2018-05-23 07:25:06 UTC IO Worker #2 DEBUG sync  4 -> Dispatching packet: 2
2018-05-23 07:25:06 UTC IO Worker #2 TRACE sync  04 -> Transactions (1 entries)

**Comment by Tbaut** [comment] 2018-05-23 15:47
I can reproduce, here is the full log: https://gist.github.com/Tbaut/79dee1e5dac1f64fb6b2e0127a177eac

**Comment by 5chdn** [comment] 2018-06-23 16:59
That gist is gone.

Didn't we fix this deadlock? @gs201510 does this happen with the latest master?

**Comment by Tbaut** [comment] 2018-09-07 09:33
Closing as I can't reproduce.

**Closed by Tbaut** 2018-09-07 09:33 UTC
Labels: F2-bug 🐞, M4-core ⛓
