### ISSUE TITLE
Instant seal engine - private network - transactions with correct nonce sometimes get stuck

### ISSUE THREAD

**Issue by nostdm** [paritytech/parity-ethereum#9155] opened 2018-07-17 21:27 UTC
> I'm running:
>
> - **Which Parity version?**: 1.11.6
> - **Which operating system?**: MacOS / Linux
> - **How installed?**: Dockerhub
> - **Are you fully synchronized?**: Yes
> - **Which network are you connected to?**: private network with 1-3 nodes
> - **Did you try to restart the node?**: Yes

I set up a private dev network with 3 Parity nodes using the instant seal engine (the same issue occurs with a single node).  

Whenever I send a bunch of transactions from the same account in quick succession, I almost always end up with the following network state:

Given an account with a nonce of 50:
```
web3.eth.getTransactionCount("0xabc...")
50
```
There are transactions in the pending pool which look like this:
```
Nonce: 50 From: 0xabc... Hash: 0x47bcde7d4323eba4ad01b1eafd1720ab9ee0e20ba139af23eaa062357418a04b
Nonce: 51 From: 0xabc... Hash: 0xeee971ab1d9eab54d7f25a70466fabde24b6b249b620da93b2f5d5c3f50afd86
Nonce: 52 From: 0xabc... Hash: 0xb84a4298e13a61842b3c5f4400ed671bef5cfb9dd9eb25208157ac87e8342eb3
```

All the transactions are seemingly stuck (they never get mined if I don't cancel them) even though the nonce of the lowest transaction is correct and should have been mined.

Additionally, if I cancel the transaction with the lowest nonce (50 in this case) and resubmit it, it goes through without problems.

Could this be something to do with the instant seal engine? 

P.S. I've tried different versions of Parity without success (v1.11.0 - v2.0.0)

**Comment by Tbaut** [comment] 2018-07-18 08:56
Can you provide a web3.js codes to reproduce? Are you sure that all the Txs before get mined and that you do not have a nonce gap? We generally advise handling the nonce counting in your code if you wish to send a lot of Txs in a short time frame.

**Comment by Tbaut** [comment] 2018-07-19 18:27
Is there any reason why you did not use the `--chain dev`?
Your config file is full of default values and not used params, it is therefore quite hard at first glance to debug/understand what your setup has in particular.

I do not have the ability to run anything with go on my machine, unfortunately.

**Comment by nostdm** [comment] 2018-07-20 11:32
As far as I'm aware, `--chain dev` doesn't allow me to set up a custom private network with multiple parity nodes and a bootnode.

**Comment by nostdm** [comment] 2018-07-20 11:37
@Tbaut 

I used a custom config and genesis file mainly because it allows me to set up a private network with more control. But here is the same example with `--chain dev` and using a JavaScript program instead of Go:

Docker command to run the container:
```
docker run --rm -it --name parity-dev -p 8545:8545 parity/parity:v1.11.6 --chain=dev --jsonrpc-interface=0.0.0.0 --jsonrpc-apis=all
```

Script to send a couple of asynchronous transactions (`test.js`):
```
const Web3 = require("web3");

// Configuration
const config = {
  rpc: {
    host: 'localhost',
    port: '8545'
  },
  coinbase: {
    address: '0x00a329c0648769A73afAc7F9381E08FB43dBEA72',
    password: '',
  },
  sender: {
    keystore: `{"id":"f1961947-85d2-6177-5373-5660f17235bd","version":3,"crypto":{"cipher":"aes-128-ctr","cipherparams":{"iv":"bc1d49515391302a27c7d1fc11ada66d"},"ciphertext":"abe32c566e2cf76f647a00da5dd2e50fa148c293d9ee1192a7fb642b8abf6601","kdf":"pbkdf2","kdfparams":{"c":10240,"dklen":32,"prf":"hmac-sha256","salt":"1c49dfca625992974141365e45650ec49033629226ce23b7dc6df91ebe5fa595"},"mac":"c33e7acef7a53a999c005ed6b70a6b2da779d4ff252442a4e7b9221c1e22dbc0"},"address":"7464a376e9c27c8f9cbe1e38443cf994169f0839","name":"","meta":"{}"}`,
    address: '0x7464a376e9c27c8f9cbe1e38443cf994169f0839',
    password: '',
  },
};

// Create a connection to the node.
const provider = new Web3.providers.HttpProvider(`http://${config.rpc.host}:${config.rpc.port}`);
const web3 = new Web3(provider);

// creditSender credits the sender account with ETH
async function creditSender() {
  try {
    await web3.eth.personal.unlockAccount(config.coinbase.address, config.coinbase.password)
    await web3.eth.sendTransaction({from: config.coinbase.address, to: config.sender.address, value: 1000000000000000000, gasPrice: 10000, gas: 25000})
  } catch (err) {
    console.error(err)
  }
}

// sleep returns a promise that resolves after a random amount of time up to the maximum value.
function sleep(max) {
  return new Promise(resolve => setTimeout(resolve, Math.floor(Math.random() * Math.floor(max))));
}

// sign signs an Ethereum transaction with the sender's private key.
async function sign(unsignedTx) {
  try {
    // Get the private key from the keystore.
    const decrypted = await web3.eth.accounts.decrypt(config.sender.keystore, config.sender.password);
    return await decrypted.signTransaction(unsignedTx)
  } catch (err) {
    console.error(err)
  }
}

// sendRandom sends a valid transaction after a random amount of time with the specified nonce.
async function sendRandom(nonce) {
  try {
    // Sleep random time.
    await sleep(1000)
    // Construct transaction.
    const unsignedTx = {
      to: config.coinbase.address,
      gasPrice: 10000,
      gas: 25000,
      nonce: nonce,
      value: 10000000,
      data: '',
    };
    // Sign the transaction.
    let signedTx = await sign(unsignedTx)
    // Send signed transaction to the blockchain.
    console.log("Sending transaction:", signedTx.messageHash, "nonce:", nonce)
    await web3.eth.sendSignedTransaction(signedTx.rawTransaction)
  } catch (err) {
    console.error(err)
  }
}

async function run() {
  try {
    // Give the sender account some ETH for gas fees.
    await creditSender()
  
    // Lookup current sender nonce.
    const nonce = await web3.eth.getTransactionCount(config.sender.address)
  
    // Send a couple of async transactions in random order.
    for (let i = 0; i < 5; i++) {
      sendRandom(nonce+i).catch(err => {console.log(err)})
    }
  } catch (err) {
    console.error(err)
  }
}

run().catch(err => {console.error(err)})
```

Dependencies (`package.json`):
```
{
  "main": "test.js",
  "dependencies": {
    "web3": "^1.0.0-beta.34"
  }
}
```

CURL command to check pending transactions:
```
curl -s --data '{"method":"parity_allTransactions","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
```

**Comment by Tbaut** [comment] 2018-07-23 10:29
Thanks a lot for the detailed post.
I tested with web3 1.0.0-beta.33 as the 34 was causing some troubles and parity v2.0.
I could also reproduce even without sending the Txs in random order (commenting out the `await sleep(1000)`).

@tomusdrw can you have a look?

**Comment by tomusdrw** [comment] 2018-07-23 10:38
Does running with `--force-sealing` help? Most likely some issues in miner (we decide that we don't need to create a pending block). InstantSeal had such issues in the past as well.

**Comment by Tbaut** [comment] 2018-07-23 11:48
Got it, `--force-sealing` didn't help, unfortunately. @nostdm you will probably have to go for a PoA based chain if you wish to continue the testing.

**Comment by nostdm** [comment] 2018-07-23 12:15
@Tbaut Could you point me in the direction of how to go about setting up Parity PoA network? Alternatively are there any CPU miners I could use for the private network instead of PoA? Thanks a lot.

**Comment by Tbaut** [comment] 2018-07-23 13:55
The quickest would be to follow the PoA tutorial: https://wiki.parity.io/Demo-PoA-tutorial.

**Comment by Tbaut** [comment] 2018-08-03 15:40
Closing as "not a bug" but a feature we decided not to develop for now.

**Closed by Tbaut** 2018-08-03 15:40 UTC
Labels: F2-bug, M4-core, P5-sometimesoon
