### ISSUE TITLE
Mainnet sync stuck at random snapshots

### ISSUE THREAD

**Issue by pabloruiz55** [paritytech/parity-ethereum#9238] opened 2018-07-27 11:46 UTC
> I'm running:
>
> - **Which Parity version?**: Parity/v1.11.7-stable-085035f-20180717/x86_64-macos/rustc1.27.1
> - **Which operating system?**: / MacOS /
> - **How installed?**: via installer
> - **Are you fully synchronized?**: no
> - **Which network are you connected to?**: ethereum
> - **Did you try to restart the node?**: yes

Running Parity like so:
`parity --rpcapi "eth,net,web3,personal,parity" --unlock 0x123.... --password [password file]`

I've been trying to sync mainnet for days now using the terminal. I'm at block #5940424 and it's trying to sync a big snapshot. At some point, during random snapshots (not always the same) it just gets stuck. For example, left it for 5 hours and it's always showing the same message over and over: 

`2018-07-27 08:19:32  Syncing snapshot 689/1818  #5940424   26/50 peers   3 MiB chain 68 MiB db 0 bytes queue 10 KiB sync  RPC:  0 conn,  0 req/s,   0 µs`

No error messages afaict.
Tried to stop and restart several times. Switched to different versions 1.1.x.

Any pointers? Thanks!

**Comment by ordian** [comment] 2018-07-27 12:10
This is duplicate of #8938. Try [this suggestion](https://github.com/paritytech/parity-ethereum/issues/8938#issuecomment-403017502).

**Closed** 2018-07-27 14:21 UTC
Labels: M4-core, Z7-duplicate

**Comment by arzjoo** [comment] 2020-03-17 06:58
```
 run parity -lsync=trace
```

```
looking for:  "IO Worker #3 TRACE sync  Checking snapshot sync: X (peer: Y)" 
```

```
Search for the largest number Y  in (peer: Y) 
then copy X
```

```
 stop parity and remove -lsync=trace
```


```
open ".../.local/share/io.parity.ethereum/config.toml "
and update config.toml with warp_barrier = X
```

```
 run  : parity
```

**Comment by mtb-pro** [comment] 2020-03-17 07:02
```
 run parity -lsync=trace
```

```
looking for:  "IO Worker #3 TRACE sync  Checking snapshot sync: X (peer: Y)" 
```

```
Search for the largest number Y  in (peer: Y) 
then copy X
```

```
 stop parity and remove -lsync=trace
```


```
open ".../.local/share/io.parity.ethereum/config.toml "
and update config.toml with warp_barrier = X
```

```
 run  : parity
```

**Comment by dvdplm** [comment] 2020-03-17 08:12
@mtb-pro I don't think that's very good advice; it is close to what the code already does. It may be that in times of sever dearth of snapshots on the network your client might pick one that is not the best possible available and this is where `--warp-barrier` comes in handy.
